/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_gmg;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import net.proteanit.sql.DbUtils;
import java.util.logging.*;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/*---------*/
/**
 *
 * @author Mike
 */
public class JF_Ciclos extends javax.swing.JFrame {

    private Connection conexion = null;
    private Statement st;
    private ResultSet rs;

    public void Conectar() {

        try {

            conexion = DriverManager.getConnection("jdbc:mysql://localhost/sistema_gmg", "root", "1405");

            st = conexion.createStatement();

            rs = st.executeQuery("Select * from ciclos");
            jt_ciclos.setModel(DbUtils.resultSetToTableModel(rs));
            rs.next();

            rs = st.executeQuery("Select * from ciclos");
            rs.next();

            this.jtf_id_ciclo.setText(rs.getString("id_ciclo"));

            this.jtf_ciclo.setText(rs.getString("ciclo"));

            this.jtf_finicio.setText(rs.getString("fecha_inicio"));

            this.jtf_ftermino.setText(rs.getString("fecha_termino"));

            jb_cancelar.setEnabled(false);
            jb_guardar.setEnabled(false);
            jb_actualizar.setEnabled(false);

            jb_primero.setEnabled(true);
            jb_ultimo.setEnabled(true);
            jb_siguiente.setEnabled(true);
            jb_anterior.setEnabled(true);
            jb_buscar.setEnabled(true);
            jb_borrar.setEnabled(true);
            jb_editar.setEnabled(true);
            jb_nuevo.setEnabled(true);
            jtf_id_ciclo.setEditable(false);
            jtf_id_ciclo.setVisible(false);
            jtf_ciclo.setEditable(false);
            jtf_finicio.setEditable(false);
            jtf_ftermino.setEditable(false);

        } catch (SQLException err) {

            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }
    
    

    public JF_Ciclos() {
        initComponents();
        Conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_tabla = new javax.swing.JPanel();
        jl_menu = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buttons_2 = new javax.swing.JPanel();
        jb_nuevo = new javax.swing.JButton();
        jb_editar = new javax.swing.JButton();
        jb_borrar = new javax.swing.JButton();
        jb_actualizar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jb_guardar = new javax.swing.JButton();
        jb_regresar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jb_primero = new javax.swing.JButton();
        jb_anterior = new javax.swing.JButton();
        jb_siguiente = new javax.swing.JButton();
        jb_ultimo = new javax.swing.JButton();
        jl_ciclo = new javax.swing.JLabel();
        jl_finicio = new javax.swing.JLabel();
        jl_ftermino = new javax.swing.JLabel();
        jtf_id_ciclo = new javax.swing.JTextField();
        jtf_ciclo = new javax.swing.JTextField();
        jtf_finicio = new javax.swing.JTextField();
        jtf_ftermino = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jb_buscar = new javax.swing.JButton();
        jtf_buscar = new javax.swing.JTextField();
        js_ciclos = new javax.swing.JScrollPane();
        jt_ciclos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ciclos");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(1018, 516));
        setResizable(false);

        panel_tabla.setBackground(new java.awt.Color(10, 34, 64));

        jl_menu.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        jl_menu.setForeground(new java.awt.Color(255, 255, 255));
        jl_menu.setText("Menú");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        buttons_2.setBackground(new java.awt.Color(106, 116, 145));

        jb_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/new.png"))); // NOI18N
        jb_nuevo.setText("Nuevo");
        jb_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_nuevoMouseClicked(evt);
            }
        });

        jb_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit.png"))); // NOI18N
        jb_editar.setText("Editar");
        jb_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_editarMouseClicked(evt);
            }
        });

        jb_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trash.png"))); // NOI18N
        jb_borrar.setText("Borrar");
        jb_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_borrarMouseClicked(evt);
            }
        });

        jb_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ciclo.png"))); // NOI18N
        jb_actualizar.setText("Actualizar");
        jb_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_actualizarMouseClicked(evt);
            }
        });
        jb_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_actualizarActionPerformed(evt);
            }
        });

        jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N
        jb_cancelar.setText("Cancelar");
        jb_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cancelarMouseClicked(evt);
            }
        });

        jb_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-Guardar Filled-50.png"))); // NOI18N
        jb_guardar.setText("Guardar");
        jb_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarMouseClicked(evt);
            }
        });
        jb_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttons_2Layout = new javax.swing.GroupLayout(buttons_2);
        buttons_2.setLayout(buttons_2Layout);
        buttons_2Layout.setHorizontalGroup(
            buttons_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttons_2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(buttons_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_borrar)
                    .addComponent(jb_editar)
                    .addComponent(jb_nuevo))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttons_2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(buttons_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_guardar)
                    .addComponent(jb_cancelar)
                    .addComponent(jb_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        buttons_2Layout.setVerticalGroup(
            buttons_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttons_2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jb_nuevo)
                .addGap(18, 18, 18)
                .addComponent(jb_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_borrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_guardar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jb_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/home.png"))); // NOI18N
        jb_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_tablaLayout = new javax.swing.GroupLayout(panel_tabla);
        panel_tabla.setLayout(panel_tablaLayout);
        panel_tablaLayout.setHorizontalGroup(
            panel_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tablaLayout.createSequentialGroup()
                .addGap(0, 71, Short.MAX_VALUE)
                .addComponent(buttons_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(panel_tablaLayout.createSequentialGroup()
                .addGroup(panel_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_tablaLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(panel_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_tablaLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jl_menu))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_tablaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jb_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_tablaLayout.setVerticalGroup(
            panel_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tablaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jb_regresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jl_menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttons_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel1.setBackground(new java.awt.Color(32, 47, 90));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Desplazamiento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 46, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 83, 141, 18));

        jb_primero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-Galón izquierdo-26.png"))); // NOI18N
        jb_primero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_primeroMouseClicked(evt);
            }
        });
        jb_primero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_primeroActionPerformed(evt);
            }
        });
        jPanel1.add(jb_primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 107, -1, -1));

        jb_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-Doble izquierda-48.png"))); // NOI18N
        jb_anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_anteriorMouseClicked(evt);
            }
        });
        jb_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_anteriorActionPerformed(evt);
            }
        });
        jPanel1.add(jb_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 107, -1, -1));

        jb_siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-Doble derecha-48.png"))); // NOI18N
        jb_siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_siguienteMouseClicked(evt);
            }
        });
        jb_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_siguienteActionPerformed(evt);
            }
        });
        jPanel1.add(jb_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 107, 54, -1));

        jb_ultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/derecho.png"))); // NOI18N
        jb_ultimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ultimoMouseClicked(evt);
            }
        });
        jb_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ultimoActionPerformed(evt);
            }
        });
        jPanel1.add(jb_ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 107, 54, -1));

        jl_ciclo.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jl_ciclo.setForeground(new java.awt.Color(255, 255, 255));
        jl_ciclo.setText("Ciclo:");
        jPanel1.add(jl_ciclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 92, -1, -1));

        jl_finicio.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jl_finicio.setForeground(new java.awt.Color(255, 255, 255));
        jl_finicio.setText("F. inicio");
        jPanel1.add(jl_finicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 146, -1, -1));

        jl_ftermino.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jl_ftermino.setForeground(new java.awt.Color(255, 255, 255));
        jl_ftermino.setText("F. termino");
        jPanel1.add(jl_ftermino, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 192, -1, -1));
        jPanel1.add(jtf_id_ciclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 38, 80, -1));

        jtf_ciclo.setBackground(new java.awt.Color(32, 47, 90));
        jtf_ciclo.setForeground(new java.awt.Color(255, 255, 255));
        jtf_ciclo.setBorder(null);
        jtf_ciclo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_cicloKeyTyped(evt);
            }
        });
        jPanel1.add(jtf_ciclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 123, -1));

        jtf_finicio.setBackground(new java.awt.Color(32, 47, 90));
        jtf_finicio.setForeground(new java.awt.Color(255, 255, 255));
        jtf_finicio.setBorder(null);
        jtf_finicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_finicioKeyTyped(evt);
            }
        });
        jPanel1.add(jtf_finicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 146, -1));

        jtf_ftermino.setBackground(new java.awt.Color(32, 47, 90));
        jtf_ftermino.setForeground(new java.awt.Color(255, 255, 255));
        jtf_ftermino.setBorder(null);
        jtf_ftermino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_fterminoKeyTyped(evt);
            }
        });
        jPanel1.add(jtf_ftermino, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 146, -1));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 168, 141, 18));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 141, 18));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 141, 18));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jb_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        jb_buscar.setText("Buscar registro:");
        jb_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_buscarMouseClicked(evt);
            }
        });

        jtf_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_buscarKeyTyped(evt);
            }
        });

        jt_ciclos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt_ciclos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_ciclosMouseClicked(evt);
            }
        });
        js_ciclos.setViewportView(jt_ciclos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jb_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(js_ciclos, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_buscar))
                .addGap(18, 18, 18)
                .addComponent(js_ciclos, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panel_tabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_regresarActionPerformed

        JF_Principal principal = new JF_Principal();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jb_regresarActionPerformed

    private void jb_primeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_primeroMouseClicked
        if (this.jb_primero.isEnabled()) {
            primer_registro();
        } else {
        }
    }//GEN-LAST:event_jb_primeroMouseClicked

    private void jb_primeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_primeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_primeroActionPerformed

    private void jb_anteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_anteriorMouseClicked
        if (this.jb_anterior.isEnabled()) {
            anterior_registro();
        } else {
        }
    }//GEN-LAST:event_jb_anteriorMouseClicked

    private void jb_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_anteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_anteriorActionPerformed

    private void jb_siguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_siguienteMouseClicked
        if (this.jb_siguiente.isEnabled()) {
            siguiente_registro();
        } else {
        }
    }//GEN-LAST:event_jb_siguienteMouseClicked

    private void jb_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_siguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_siguienteActionPerformed

    private void jb_ultimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ultimoMouseClicked
        if (this.jb_ultimo.isEnabled()) {
            ultimo_registro();
        } else {
        }
    }//GEN-LAST:event_jb_ultimoMouseClicked

    private void jb_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ultimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_ultimoActionPerformed

    private void jb_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_buscarMouseClicked
        if (this.jb_buscar.isEnabled()) {
            buscar();
        } else {
        }
    }//GEN-LAST:event_jb_buscarMouseClicked

    private void jb_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_actualizarMouseClicked
        if (this.jb_actualizar.isEnabled()) {
            /*no agregar esta parte*/ String registro = this.jtf_ciclo.getText();
            int alerta = JOptionPane.showConfirmDialog(null, "¿Quiere actualizar el ciclo: " + registro + "?", "Actualizar", JOptionPane.WARNING_MESSAGE, JOptionPane.INFORMATION_MESSAGE);
            if (JOptionPane.OK_OPTION == alerta) {
                JOptionPane.showMessageDialog(null, "Se actualizó el ciclo " + registro + " exitosamente", "Actualizado", JOptionPane.INFORMATION_MESSAGE);
                actualizar_registro();

            } else {

            }
        } else {
        }
    }//GEN-LAST:event_jb_actualizarMouseClicked

    private void jb_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_actualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_actualizarActionPerformed

    private void jtf_buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_buscarKeyTyped
        char cadena = evt.getKeyChar();
        if (Character.isLowerCase(cadena)){
            String cad = (""+ cadena).toUpperCase();
            cadena = cad.charAt(0);
            evt.setKeyChar(cadena);
        }
    }//GEN-LAST:event_jtf_buscarKeyTyped

    private void jb_borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_borrarMouseClicked
        if (this.jb_borrar.isEnabled()) {
            String registro = this.jtf_ciclo.getText();

            int alerta = JOptionPane.showConfirmDialog(null, "¿Quiere eliminar el ciclo " + registro + "", "Se borrarrá el registro", JOptionPane.WARNING_MESSAGE, JOptionPane.ERROR_MESSAGE);

            if (JOptionPane.OK_OPTION == alerta) {
                JOptionPane.showMessageDialog(null, "Se borro el registro del ciclo " + registro + "", "Eliminado", JOptionPane.WARNING_MESSAGE);
                borrar_registro();
            } else {

            }
        } else {
        }
    }//GEN-LAST:event_jb_borrarMouseClicked

    private void jb_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_editarMouseClicked
        if (this.jb_editar.isEnabled()) {

            jtf_ciclo.setEditable(true);
            jtf_finicio.setEditable(true);
            jtf_ftermino.setEditable(true);

            jb_editar.setEnabled(false);
            jb_primero.setEnabled(false);
            jb_ultimo.setEnabled(false);
            jb_siguiente.setEnabled(false);
            jb_anterior.setEnabled(false);
            jb_buscar.setEnabled(false);
            jb_borrar.setEnabled(false);
            jb_actualizar.setEnabled(true);
            jb_cancelar.setEnabled(true);
            jb_guardar.setEnabled(false);
            jb_nuevo.setEnabled(false);
        } else {
        }
    }//GEN-LAST:event_jb_editarMouseClicked

    private void jb_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_nuevoMouseClicked
        if (this.jb_nuevo.isEnabled()) {
            nuevo_registro();
        } else {
        }
    }//GEN-LAST:event_jb_nuevoMouseClicked

    private void jb_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cancelarMouseClicked
        if (this.jb_cancelar.isEnabled()) {
            Conectar();
        } else {
        }
    }//GEN-LAST:event_jb_cancelarMouseClicked

    private void jb_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarMouseClicked
        if (this.jb_guardar.isEnabled()) {
            guardar_registro();
        } else {
        }
    }//GEN-LAST:event_jb_guardarMouseClicked

    private void jb_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_guardarActionPerformed

    private void jt_ciclosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_ciclosMouseClicked
        tabla();
    }//GEN-LAST:event_jt_ciclosMouseClicked

    private void jtf_cicloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_cicloKeyTyped
        char cadena = evt.getKeyChar();
        if (Character.isLowerCase(cadena)){
            String cad = (""+ cadena).toUpperCase();
            cadena = cad.charAt(0);
            evt.setKeyChar(cadena);
        }
    }//GEN-LAST:event_jtf_cicloKeyTyped

    private void jtf_finicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_finicioKeyTyped
        char cadena = evt.getKeyChar();
        if (Character.isLowerCase(cadena)){
            String cad = (""+ cadena).toUpperCase();
            cadena = cad.charAt(0);
            evt.setKeyChar(cadena);
        }
    }//GEN-LAST:event_jtf_finicioKeyTyped

    private void jtf_fterminoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_fterminoKeyTyped
        char cadena = evt.getKeyChar();
        if (Character.isLowerCase(cadena)){
            String cad = (""+ cadena).toUpperCase();
            cadena = cad.charAt(0);
            evt.setKeyChar(cadena);
        }
    }//GEN-LAST:event_jtf_fterminoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Ciclos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Ciclos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Ciclos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Ciclos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Ciclos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttons_2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton jb_actualizar;
    private javax.swing.JButton jb_anterior;
    private javax.swing.JButton jb_borrar;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_editar;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_nuevo;
    private javax.swing.JButton jb_primero;
    private javax.swing.JButton jb_regresar;
    private javax.swing.JButton jb_siguiente;
    private javax.swing.JButton jb_ultimo;
    private javax.swing.JLabel jl_ciclo;
    private javax.swing.JLabel jl_finicio;
    private javax.swing.JLabel jl_ftermino;
    private javax.swing.JLabel jl_menu;
    private javax.swing.JScrollPane js_ciclos;
    private javax.swing.JTable jt_ciclos;
    private javax.swing.JTextField jtf_buscar;
    private javax.swing.JTextField jtf_ciclo;
    private javax.swing.JTextField jtf_finicio;
    private javax.swing.JTextField jtf_ftermino;
    private javax.swing.JTextField jtf_id_ciclo;
    private javax.swing.JPanel panel_tabla;
    // End of variables declaration//GEN-END:variables

    private void buscar() {
        try {            
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/sistema_gmg", "root", "1405");

            st = conexion.createStatement();
            
            rs = st.executeQuery("select * from ciclos where ciclo like '%" + this.jtf_buscar.getText() + "%'");

            jtf_id_ciclo.setText(null);
            jtf_ciclo.setText(null);
            jtf_finicio.setText(null);
            jtf_ftermino.setText(null);
            
            jt_ciclos.setModel(DbUtils.resultSetToTableModel(rs));
            
            jb_cancelar.setEnabled(true);            
            rs = st.executeQuery("select *from ciclos");
        } catch (SQLException ex) {
            Logger.getLogger(JF_Alumnos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void nuevo_registro() {
        jtf_id_ciclo.setText(null);
        jtf_ciclo.setText(null);
        jtf_finicio.setText(null);
        jtf_ftermino.setText(null);

        jb_nuevo.setEnabled(false);
        jb_primero.setEnabled(false);
        jb_ultimo.setEnabled(false);
        jb_siguiente.setEnabled(false);
        jb_anterior.setEnabled(false);
        jb_buscar.setEnabled(false);
        jb_borrar.setEnabled(false);
        jb_actualizar.setEnabled(false);
        jb_cancelar.setEnabled(true);
        jb_guardar.setEnabled(true);
        jb_editar.setEnabled(false);
        
        jtf_ciclo.setEditable(true);
        jtf_finicio.setEditable(true);
        jtf_ftermino.setEditable(true);
    }

    private void actualizar_registro() {
        try {

            jtf_ciclo.getText();
            jtf_finicio.getText();
            jtf_ftermino.getText();

            st.executeUpdate("update ciclos set ciclo= '" + jtf_ciclo.getText() + "', fecha_inicio = '" + jtf_finicio.getText() + "', fecha_termino = '" + jtf_ftermino.getText() + "' where id_ciclo = "
                    + this.jtf_id_ciclo.getText());

            Conectar();
            
            this.primer_registro();

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Rellene correctamente los campos", "Error al actualizar", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void guardar_registro() {
        try {
            String ciclo = this.jtf_ciclo.getText();
            String fecha_inicio = this.jtf_finicio.getText();
            String fecha_termino = this.jtf_ftermino.getText();

            st.executeUpdate("Insert into ciclos (ciclo,fecha_inicio,fecha_termino)" + "values ('" + ciclo + "','" + fecha_termino + "','" + fecha_inicio + "');");

            Conectar();
            this.primer_registro();

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Rellene correctamente los campos", "Error al guardar", JOptionPane.INFORMATION_MESSAGE);
        }

    }

    private void siguiente_registro() {
        try {
            if (rs.isLast() == false) {
                rs.next();
                this.jtf_id_ciclo.setText(rs.getString("id_ciclo"));
                this.jtf_ciclo.setText(rs.getString("ciclo"));
                this.jtf_finicio.setText(rs.getString("fecha_inicio"));
                this.jtf_ftermino.setText(rs.getString("fecha_termino"));
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }

    private void anterior_registro() {
        try {
            if (rs.isFirst() == false) {
                rs.previous();
                this.jtf_id_ciclo.setText(rs.getString("id_ciclo"));
                this.jtf_ciclo.setText(rs.getString("ciclo"));
                this.jtf_finicio.setText(rs.getString("fecha_inicio"));
                this.jtf_ftermino.setText(rs.getString("fecha_termino"));
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }

    private void ultimo_registro() {
        try {
            if (rs.isLast() == false) {
                rs.last();
                this.jtf_id_ciclo.setText(rs.getString("id_ciclo"));
                this.jtf_ciclo.setText(rs.getString("ciclo"));
                this.jtf_finicio.setText(rs.getString("fecha_inicio"));
                this.jtf_ftermino.setText(rs.getString("fecha_termino"));
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }

    private void primer_registro() {
        try {
            if (rs.isFirst() == false) {
                rs.first();
                this.jtf_id_ciclo.setText(rs.getString("id_ciclo"));
                this.jtf_ciclo.setText(rs.getString("ciclo"));
                this.jtf_finicio.setText(rs.getString("fecha_inicio"));
                this.jtf_ftermino.setText(rs.getString("fecha_termino"));
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }

    private void borrar_registro() {
        try {
            st.executeUpdate("delete from ciclos where id_ciclo=" + this.jtf_id_ciclo.getText());
            Conectar();
            this.primer_registro();

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());

        }
    }
    
    private void tabla() {
        try {                            
        int seleccion = jt_ciclos.getSelectedRow();
        
        jtf_id_ciclo.setText(String.valueOf(jt_ciclos.getValueAt(seleccion, 0)));
        jtf_ciclo.setText(String.valueOf(jt_ciclos.getValueAt(seleccion, 1)));
        jtf_finicio.setText(String.valueOf(jt_ciclos.getValueAt(seleccion, 2)));
        jtf_ftermino.setText(String.valueOf(jt_ciclos.getValueAt(seleccion, 3)));
        
        rs = st.executeQuery("select * from ciclos");
        jt_ciclos.setModel(DbUtils.resultSetToTableModel(rs));
        rs = st.executeQuery("select * from ciclos");        
        } catch (SQLException ex) {
            Logger.getLogger(JF_Alumnos.class.getName()).log(Level.SEVERE, null, ex);
        }                                    
    }
}
