package sistema_gmg;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

public class JF_Grupos extends javax.swing.JFrame {

    private Connection conexion = null;
    private Statement st;
    private ResultSet rs;
    private TableModel ciclos;

    public void Conectar() {
        try {
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/sistema_gmg", "root", "1405");
            st = conexion.createStatement();

            rs = st.executeQuery("SELECT * FROM sistema_gmg.vista_asignacion order by grado;");
            jt_profesor_grupos.setModel(DbUtils.resultSetToTableModel(rs));
            rs.next();

            rs = st.executeQuery("SELECT * FROM sistema_gmg.vista_grupos order by grado;");
            jt_grupos.setModel(DbUtils.resultSetToTableModel(rs));
            rs.next();

            rs = st.executeQuery("SELECT * FROM sistema_gmg.vista_grupos order by grado;");
            rs.next();

            this.jtf_id_grupo.setText(rs.getString("id_grupo"));

            this.jtf_grado.setText(rs.getString("grado"));

            this.jtf_grupo.setText(rs.getString("grupo"));
            
            this.jtf_ciclo.setText(rs.getString("ciclo"));
            

        } catch (SQLException err) {

            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }

    public void botones() {

        jp_cb.setVisible(false);
        jb_cancelar.setEnabled(false);
        jb_guardar.setEnabled(false);
        jb_actualizar.setEnabled(false);

        jb_primero.setEnabled(true);
        jb_ultimo.setEnabled(true);
        jb_siguiente.setEnabled(true);
        jb_anterior.setEnabled(true);
        jb_buscar.setEnabled(true);
        jb_borrar.setEnabled(true);
        jb_editar.setEnabled(true);
        jb_nuevo.setEnabled(true);
        jb_profe.setEnabled(true);

        jp_ciclo.setVisible(false);
        jtf_id_profesor.setEditable(false);
        jtf_id_profesor.setVisible(false);
        jtf_id_profesor_extra.setVisible(false);
        jcb_id_extras.setVisible(false);
        jcb_id_profe.setVisible(false);
        jtf_id_ciclo.setEditable(false);
        jtf_id_ciclo.setVisible(false);
        jtf_id_grupo.setEditable(false);
        jtf_id_grupo.setVisible(false);
        jtf_grado.setEditable(false);
        jtf_grupo.setEditable(false);
    }

    public void combobox() {
        try {
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/sistema_gmg", "root", "1405");

            st = conexion.createStatement();

            rs = st.executeQuery("Select ciclo from ciclos;");
            while (rs.next()) {
                this.jcb_ciclo.addItem(rs.getString("ciclo"));
            }
            rs = st.executeQuery("Select id_profesor,nombre_profe,ap_paterno_prof,ap_materno_prof from profesores where id_tipo = '000001';");
            while (rs.next()) {
                this.jcb_nombre_profesor.addItem(rs.getString(2) + " " + rs.getString(3) + " " + rs.getString(4));
                this.jcb_id_profe.addItem(rs.getString("id_profesor"));
            }

            rs = st.executeQuery("Select id_profesor,nombre_profe,ap_paterno_prof,ap_materno_prof from profesores where id_tipo = 000002 or id_tipo = 000003 ;");
            while (rs.next()) {
                this.jcb_extras.addItem(rs.getString(2) + " " + rs.getString(3) + " " + rs.getString(4));
                this.jcb_id_extras.addItem(rs.getString("id_profesor"));
            }
            int index2 = this.jcb_extras.getSelectedIndex();
            this.jtf_id_profesor_extra.setText("" + index2);
        } catch (SQLException err) {

            //JOptionPane.showMessageDialog(null, "Error " + err.getMessage());

        }
    }

    public JF_Grupos() {
        initComponents();        
        combobox();
        botones();
        Conectar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_tabla = new javax.swing.JPanel();
        jl_menu = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buttons_2 = new javax.swing.JPanel();
        jb_nuevo = new javax.swing.JButton();
        jb_profe = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jb_borrar = new javax.swing.JButton();
        jb_actualizar = new javax.swing.JButton();
        jb_editar = new javax.swing.JButton();
        jb_guardar = new javax.swing.JButton();
        jb_regresar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jb_siguiente = new javax.swing.JButton();
        jb_ultimo = new javax.swing.JButton();
        jb_primero = new javax.swing.JButton();
        jb_anterior = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jl_grado = new javax.swing.JLabel();
        lj_grupo = new javax.swing.JLabel();
        jtf_grupo = new javax.swing.JTextField();
        jtf_grado = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jtf_id_grupo = new javax.swing.JTextField();
        jp_ciclo = new javax.swing.JPanel();
        jtf_id_ciclo = new javax.swing.JTextField();
        jcb_ciclo = new javax.swing.JComboBox<>();
        jl_ciclo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtf_ciclo = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jb_buscar = new javax.swing.JButton();
        jtf_buscar = new javax.swing.JTextField();
        jp_cb = new javax.swing.JPanel();
        jl_profesor_asig = new javax.swing.JLabel();
        jb_asignar2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jcb_extras = new javax.swing.JComboBox<>();
        jcb_id_extras = new javax.swing.JComboBox<>();
        jl_profesor_asig1 = new javax.swing.JLabel();
        jl_profe_aca = new javax.swing.JLabel();
        jb_borrar_asig = new javax.swing.JButton();
        jtf_id_profesor = new javax.swing.JTextField();
        jcb_nombre_profesor = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jcb_id_profe = new javax.swing.JComboBox<>();
        jtf_id_profesor_extra = new javax.swing.JTextField();
        jb_asignar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_grupos = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_profesor_grupos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Grupos");
        setName("jf_grupos"); // NOI18N

        panel_tabla.setBackground(new java.awt.Color(10, 34, 64));

        jl_menu.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        jl_menu.setForeground(new java.awt.Color(255, 255, 255));
        jl_menu.setText("Menú");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        buttons_2.setBackground(new java.awt.Color(106, 116, 145));

        jb_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/new.png"))); // NOI18N
        jb_nuevo.setText("Nuevo");
        jb_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_nuevoMouseClicked(evt);
            }
        });

        jb_profe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit.png"))); // NOI18N
        jb_profe.setText("Agregar/Editar profesor");
        jb_profe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_profeMouseClicked(evt);
            }
        });
        jb_profe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_profeActionPerformed(evt);
            }
        });

        jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N
        jb_cancelar.setText("Cancelar");
        jb_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cancelarMouseClicked(evt);
            }
        });

        jb_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trash.png"))); // NOI18N
        jb_borrar.setText("Borrar");
        jb_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_borrarMouseClicked(evt);
            }
        });

        jb_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ciclo.png"))); // NOI18N
        jb_actualizar.setText("Actualizar");
        jb_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_actualizarMouseClicked(evt);
            }
        });
        jb_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_actualizarActionPerformed(evt);
            }
        });

        jb_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit.png"))); // NOI18N
        jb_editar.setText("Editar");
        jb_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_editarMouseClicked(evt);
            }
        });

        jb_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-Guardar Filled-50.png"))); // NOI18N
        jb_guardar.setText("Guardar");
        jb_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarMouseClicked(evt);
            }
        });
        jb_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttons_2Layout = new javax.swing.GroupLayout(buttons_2);
        buttons_2.setLayout(buttons_2Layout);
        buttons_2Layout.setHorizontalGroup(
            buttons_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttons_2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(buttons_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_profe)
                    .addGroup(buttons_2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(buttons_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_guardar)
                            .addComponent(jb_nuevo)
                            .addGroup(buttons_2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jb_editar))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttons_2Layout.createSequentialGroup()
                        .addGroup(buttons_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jb_borrar)
                            .addComponent(jb_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)))
                .addGap(19, 19, 19))
            .addGroup(buttons_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buttons_2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jb_cancelar)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        buttons_2Layout.setVerticalGroup(
            buttons_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttons_2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jb_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_editar)
                .addGap(59, 59, 59)
                .addComponent(jb_borrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_profe, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(buttons_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buttons_2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jb_cancelar)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jb_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/home.png"))); // NOI18N
        jb_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_tablaLayout = new javax.swing.GroupLayout(panel_tabla);
        panel_tabla.setLayout(panel_tablaLayout);
        panel_tablaLayout.setHorizontalGroup(
            panel_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tablaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jb_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tablaLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(panel_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttons_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_tablaLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(panel_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_tablaLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jl_menu))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22))
        );
        panel_tablaLayout.setVerticalGroup(
            panel_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tablaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jb_regresar)
                .addGap(18, 18, 18)
                .addComponent(jl_menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttons_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(32, 47, 90));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-Doble derecha-48.png"))); // NOI18N
        jb_siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_siguienteMouseClicked(evt);
            }
        });
        jPanel1.add(jb_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        jb_ultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/derecho.png"))); // NOI18N
        jb_ultimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ultimoMouseClicked(evt);
            }
        });
        jb_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ultimoActionPerformed(evt);
            }
        });
        jPanel1.add(jb_ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));

        jb_primero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-Galón izquierdo-26.png"))); // NOI18N
        jb_primero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_primeroMouseClicked(evt);
            }
        });
        jPanel1.add(jb_primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        jb_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-Doble izquierda-48.png"))); // NOI18N
        jb_anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_anteriorMouseClicked(evt);
            }
        });
        jPanel1.add(jb_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Desplazamiento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 142, 10));

        jl_grado.setForeground(new java.awt.Color(255, 255, 255));
        jl_grado.setText("Grado:");
        jPanel1.add(jl_grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        lj_grupo.setForeground(new java.awt.Color(255, 255, 255));
        lj_grupo.setText("Grupo:");
        jPanel1.add(lj_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jtf_grupo.setBackground(new java.awt.Color(32, 47, 90));
        jtf_grupo.setForeground(new java.awt.Color(255, 255, 255));
        jtf_grupo.setBorder(null);
        jtf_grupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_grupoKeyPressed(evt);
            }
        });
        jPanel1.add(jtf_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 110, 20));

        jtf_grado.setBackground(new java.awt.Color(32, 47, 90));
        jtf_grado.setForeground(new java.awt.Color(255, 255, 255));
        jtf_grado.setBorder(null);
        jtf_grado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_gradoActionPerformed(evt);
            }
        });
        jtf_grado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_gradoKeyTyped(evt);
            }
        });
        jPanel1.add(jtf_grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 110, 20));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 142, 10));

        jtf_id_grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_id_grupoActionPerformed(evt);
            }
        });
        jPanel1.add(jtf_id_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, -1));

        jp_ciclo.setBackground(new java.awt.Color(32, 47, 90));

        jcb_ciclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_cicloActionPerformed(evt);
            }
        });

        jl_ciclo.setForeground(new java.awt.Color(255, 255, 255));
        jl_ciclo.setText("Ciclo:");

        javax.swing.GroupLayout jp_cicloLayout = new javax.swing.GroupLayout(jp_ciclo);
        jp_ciclo.setLayout(jp_cicloLayout);
        jp_cicloLayout.setHorizontalGroup(
            jp_cicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cicloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_ciclo)
                .addGap(7, 7, 7)
                .addComponent(jcb_ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jtf_id_ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jp_cicloLayout.setVerticalGroup(
            jp_cicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cicloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_cicloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_cicloLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jl_ciclo))
                    .addComponent(jcb_ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_id_ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jp_ciclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ciclo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jtf_ciclo.setBackground(new java.awt.Color(32, 47, 90));
        jtf_ciclo.setForeground(new java.awt.Color(255, 255, 255));
        jtf_ciclo.setBorder(null);
        jtf_ciclo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_cicloKeyPressed(evt);
            }
        });
        jPanel1.add(jtf_ciclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 110, 20));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 142, 10));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jb_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        jb_buscar.setText("Buscar Registro");
        jb_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_buscarMouseClicked(evt);
            }
        });
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed(evt);
            }
        });

        jtf_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_buscarKeyTyped(evt);
            }
        });

        jp_cb.setBackground(new java.awt.Color(255, 255, 255));

        jl_profesor_asig.setText("Profesor:");

        jb_asignar2.setText("Asignar");
        jb_asignar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_asignar2MouseClicked(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Profesor Extra-cocurricular");

        jcb_extras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_extrasActionPerformed(evt);
            }
        });

        jl_profesor_asig1.setText("Profesor:");

        jl_profe_aca.setForeground(new java.awt.Color(0, 51, 255));
        jl_profe_aca.setText("Profesor de Academia");

        jb_borrar_asig.setText("Quitar asignacion");
        jb_borrar_asig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_borrar_asigMouseClicked(evt);
            }
        });

        jcb_nombre_profesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_nombre_profesorActionPerformed(evt);
            }
        });

        jButton1.setText("Quitar asignacion");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jb_asignar.setText("Asignar");
        jb_asignar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_asignarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_cbLayout = new javax.swing.GroupLayout(jp_cb);
        jp_cb.setLayout(jp_cbLayout);
        jp_cbLayout.setHorizontalGroup(
            jp_cbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cbLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_cbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_cbLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel2))
                    .addGroup(jp_cbLayout.createSequentialGroup()
                        .addGroup(jp_cbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_cbLayout.createSequentialGroup()
                                .addGroup(jp_cbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_cbLayout.createSequentialGroup()
                                        .addComponent(jtf_id_profesor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27))
                                    .addGroup(jp_cbLayout.createSequentialGroup()
                                        .addComponent(jl_profesor_asig)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jp_cbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcb_nombre_profesor, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcb_id_profe, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jp_cbLayout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jl_profe_aca))
                            .addGroup(jp_cbLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jp_cbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_cbLayout.createSequentialGroup()
                                        .addComponent(jtf_id_profesor_extra, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27))
                                    .addGroup(jp_cbLayout.createSequentialGroup()
                                        .addComponent(jl_profesor_asig1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jp_cbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcb_extras, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcb_id_extras, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(52, 52, 52)
                        .addGroup(jp_cbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_cbLayout.createSequentialGroup()
                                .addComponent(jb_asignar2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(jp_cbLayout.createSequentialGroup()
                                .addComponent(jb_asignar)
                                .addGap(18, 18, 18)
                                .addComponent(jb_borrar_asig)))))
                .addContainerGap())
        );
        jp_cbLayout.setVerticalGroup(
            jp_cbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_profe_aca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_cbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_nombre_profesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_profesor_asig)
                    .addComponent(jb_asignar)
                    .addComponent(jb_borrar_asig))
                .addGap(22, 22, 22)
                .addGroup(jp_cbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_id_profe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_id_profesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_cbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_extras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_profesor_asig1)
                    .addComponent(jb_asignar2)
                    .addComponent(jButton1))
                .addGap(22, 22, 22)
                .addGroup(jp_cbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_id_extras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_id_profesor_extra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jt_grupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt_grupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_gruposMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_grupos);

        jt_profesor_grupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt_profesor_grupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_profesor_gruposMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_profesor_grupos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jb_buscar)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jp_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_buscar)
                    .addComponent(jtf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jp_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane3))
            .addComponent(panel_tabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_nuevoMouseClicked
        if (this.jb_nuevo.isEnabled()) {
            nuevo_registro();
        } else {
        }
    }//GEN-LAST:event_jb_nuevoMouseClicked

    private void jb_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_regresarActionPerformed

        JF_Principal principal = new JF_Principal();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jb_regresarActionPerformed

    private void jb_anteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_anteriorMouseClicked
        //se tiene que poner a todos los eventos mouse clicked condicion if
        if (this.jb_anterior.isEnabled()) {
            anterior_registro();
        } else {
        }
    }//GEN-LAST:event_jb_anteriorMouseClicked

    private void jb_primeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_primeroMouseClicked
        if (this.jb_primero.isEnabled()) {
            primer_registro();
        } else {
        }
    }//GEN-LAST:event_jb_primeroMouseClicked

    private void jb_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ultimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_ultimoActionPerformed

    private void jb_ultimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ultimoMouseClicked
        if (this.jb_ultimo.isEnabled()) {
            ultimo_registro();
        } else {
        }
    }//GEN-LAST:event_jb_ultimoMouseClicked

    private void jb_siguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_siguienteMouseClicked
        if (this.jb_siguiente.isEnabled()) {
            siguiente_registro();
        } else {
        }
    }//GEN-LAST:event_jb_siguienteMouseClicked

    private void jtf_gradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_gradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_gradoActionPerformed

    private void jtf_gradoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_gradoKeyTyped
        char cadena = evt.getKeyChar();
        if (Character.isLowerCase(cadena)) {
            String cad = ("" + cadena).toUpperCase();
            cadena = cad.charAt(0);
            evt.setKeyChar(cadena);
        }
    }//GEN-LAST:event_jtf_gradoKeyTyped

    private void jtf_grupoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_grupoKeyPressed
        char cadena = evt.getKeyChar();
        if (Character.isLowerCase(cadena)) {
            String cad = ("" + cadena).toUpperCase();
            cadena = cad.charAt(0);
            evt.setKeyChar(cadena);
        }
    }//GEN-LAST:event_jtf_grupoKeyPressed

    private void jb_profeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_profeMouseClicked
        if (this.jb_profe.isEnabled()) {
            jp_cb.setVisible(true);
            jcb_id_profe.setVisible(false);
        } else {
        }
    }//GEN-LAST:event_jb_profeMouseClicked

    private void jb_profeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_profeActionPerformed
        if (this.jb_asignar.isEnabled()) {
            jb_cancelar.setEnabled(true);
        } else {
        }
    }//GEN-LAST:event_jb_profeActionPerformed

    private void jb_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_buscarMouseClicked
        if (this.jb_buscar.isEnabled()) {
            buscar();
        } else {
        }
    }//GEN-LAST:event_jb_buscarMouseClicked

    private void jb_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_buscarActionPerformed

    private void jtf_buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_buscarKeyTyped
        char cadena = evt.getKeyChar();
        if (Character.isLowerCase(cadena)) {
            String cad = ("" + cadena).toUpperCase();
            cadena = cad.charAt(0);
            evt.setKeyChar(cadena);
        }
    }//GEN-LAST:event_jtf_buscarKeyTyped

    private void jtf_id_grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_id_grupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_id_grupoActionPerformed

    private void jcb_nombre_profesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_nombre_profesorActionPerformed

        try {
            int index = this.jcb_nombre_profesor.getSelectedIndex();
            this.jtf_id_profesor.setText("" + index);
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/sistema_gmg", "root", "1405");
            st = conexion.createStatement();
            this.jcb_id_profe.setSelectedIndex(index);

        } catch (Exception e) {
          //  JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jcb_nombre_profesorActionPerformed

    private void jcb_extrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_extrasActionPerformed
        try {
            int index = this.jcb_extras.getSelectedIndex();
            this.jtf_id_profesor_extra.setText("" + index);
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/sistema_gmg", "root", "1405");
            st = conexion.createStatement();
            this.jcb_id_extras.setSelectedIndex(index);

        } catch (Exception e) {
           // JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jcb_extrasActionPerformed

    private void jb_asignar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_asignar2MouseClicked
        if (this.jb_asignar.isEnabled()) {
            agregar_profesor2();
        } else {
        }
    }//GEN-LAST:event_jb_asignar2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        borrar_asig2();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jb_borrar_asigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_borrar_asigMouseClicked
        if (this.jb_borrar_asig.isEnabled()) {
            borrar_asig();
        } else {
        }
    }//GEN-LAST:event_jb_borrar_asigMouseClicked

    private void jb_asignarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_asignarMouseClicked
        if (this.jb_asignar.isEnabled()) {
            agregar_profesor();
        } else {
        }
    }//GEN-LAST:event_jb_asignarMouseClicked

    private void jt_gruposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_gruposMouseClicked
        tabla();
    }//GEN-LAST:event_jt_gruposMouseClicked

    private void jt_profesor_gruposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_profesor_gruposMouseClicked

    }//GEN-LAST:event_jt_profesor_gruposMouseClicked

    private void jb_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cancelarMouseClicked
        if (this.jb_cancelar.isEnabled()) {
            botones();
        } else {
        }
    }//GEN-LAST:event_jb_cancelarMouseClicked

    private void jb_borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_borrarMouseClicked
        if (this.jb_borrar.isEnabled()) {
            String registro = this.jtf_grado.getText();

            int alerta = JOptionPane.showConfirmDialog(null, "¿Quiere eliminar el " + registro + " grado", "Se borrarrá el registro", JOptionPane.WARNING_MESSAGE, JOptionPane.ERROR_MESSAGE);

            if (JOptionPane.OK_OPTION == alerta) {
                borrar_registro();

            } else {

            }
        } else {
        }
    }//GEN-LAST:event_jb_borrarMouseClicked

    private void jb_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_actualizarMouseClicked
        if (this.jb_actualizar.isEnabled()) {
            String registro = this.jtf_grado.getText();
            int alerta = JOptionPane.showConfirmDialog(null, "¿Quiere actualizar el " + registro + " grado?", "Actualizar", JOptionPane.WARNING_MESSAGE, JOptionPane.INFORMATION_MESSAGE);
            if (JOptionPane.OK_OPTION == alerta) {
                JOptionPane.showMessageDialog(null, "Se actualizó el " + registro + " grado exitosamente", "Actualizado", JOptionPane.INFORMATION_MESSAGE);
                actualizar_registro();

            } else {

            }
        } else {
        }
    }//GEN-LAST:event_jb_actualizarMouseClicked

    private void jb_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_actualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_actualizarActionPerformed

    private void jb_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_editarMouseClicked
        if (this.jb_editar.isEnabled()) {
            jtf_grado.setEditable(true);
            jtf_grupo.setEditable(true);

            jp_ciclo.setVisible(true);
            jb_primero.setEnabled(false);
            jb_ultimo.setEnabled(false);
            jb_siguiente.setEnabled(false);
            jb_anterior.setEnabled(false);
            jb_buscar.setEnabled(false);
            jb_borrar.setEnabled(false);
            jb_actualizar.setEnabled(true);
            jb_cancelar.setEnabled(true);
            jb_guardar.setEnabled(false);
            jb_nuevo.setEnabled(false);
            jb_profe.setEnabled(false);
        } else {
        }
    }//GEN-LAST:event_jb_editarMouseClicked

    private void jb_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarMouseClicked
        if (this.jb_guardar.isEnabled()) {
            guardar_registro();
        } else {
        }
    }//GEN-LAST:event_jb_guardarMouseClicked

    private void jb_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_guardarActionPerformed

    private void jcb_cicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_cicloActionPerformed

        try {
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/sistema_gmg", "root", "1405");
            st = conexion.createStatement();
            ResultSet rs1 = st.executeQuery("select id_ciclo from ciclos where ciclo= '" + this.jcb_ciclo.getSelectedItem() + "'");
            rs1.next();
            this.jtf_id_ciclo.setText(String.valueOf(rs1.getString("id_ciclo")));
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jcb_cicloActionPerformed

    private void jtf_cicloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_cicloKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_cicloKeyPressed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Grupos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttons_2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton jb_actualizar;
    private javax.swing.JButton jb_anterior;
    private javax.swing.JButton jb_asignar;
    private javax.swing.JButton jb_asignar2;
    private javax.swing.JButton jb_borrar;
    private javax.swing.JButton jb_borrar_asig;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_editar;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_nuevo;
    private javax.swing.JButton jb_primero;
    private javax.swing.JButton jb_profe;
    private javax.swing.JButton jb_regresar;
    private javax.swing.JButton jb_siguiente;
    private javax.swing.JButton jb_ultimo;
    private javax.swing.JComboBox<String> jcb_ciclo;
    private javax.swing.JComboBox<String> jcb_extras;
    private javax.swing.JComboBox<String> jcb_id_extras;
    private javax.swing.JComboBox<String> jcb_id_profe;
    private javax.swing.JComboBox<String> jcb_nombre_profesor;
    private javax.swing.JLabel jl_ciclo;
    private javax.swing.JLabel jl_grado;
    private javax.swing.JLabel jl_menu;
    private javax.swing.JLabel jl_profe_aca;
    private javax.swing.JLabel jl_profesor_asig;
    private javax.swing.JLabel jl_profesor_asig1;
    private javax.swing.JPanel jp_cb;
    private javax.swing.JPanel jp_ciclo;
    private javax.swing.JTable jt_grupos;
    private javax.swing.JTable jt_profesor_grupos;
    private javax.swing.JTextField jtf_buscar;
    private javax.swing.JTextField jtf_ciclo;
    private javax.swing.JTextField jtf_grado;
    private javax.swing.JTextField jtf_grupo;
    private javax.swing.JTextField jtf_id_ciclo;
    private javax.swing.JTextField jtf_id_grupo;
    private javax.swing.JTextField jtf_id_profesor;
    private javax.swing.JTextField jtf_id_profesor_extra;
    private javax.swing.JLabel lj_grupo;
    private javax.swing.JPanel panel_tabla;
    // End of variables declaration//GEN-END:variables

    private void nuevo_registro() {
        jtf_id_grupo.setText(null);
        jtf_grupo.setText(null);
        jtf_grado.setText(null);

        jb_primero.setEnabled(false);
        jb_ultimo.setEnabled(false);
        jb_siguiente.setEnabled(false);
        jb_anterior.setEnabled(false);
        jb_buscar.setEnabled(false);
        jb_borrar.setEnabled(false);
        jb_actualizar.setEnabled(false);
        jb_cancelar.setEnabled(true);
        jb_guardar.setEnabled(true);
        jb_editar.setEnabled(false);
        jb_profe.setEnabled(false);

        jtf_grado.setEditable(true);
        jtf_grupo.setEditable(true);
        jp_ciclo.setVisible(true);

    }

    private void actualizar_registro() {
        try {
            jtf_grupo.getText();
            jtf_grado.getText();
            jtf_id_ciclo.getText();

            st.executeUpdate("update grupos set grado = '" + jtf_grado.getText() + "',"
                    + "grupo = '" + jtf_grupo.getText() + "', id_ciclo = '" + jtf_id_ciclo.getText() + "'"
                    + "where id_grupo = '" + jtf_id_grupo.getText() + "'");

            Conectar();
            botones();
            this.primer_registro();

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Rellene correctamente los campos", "Error al actualizar", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void guardar_registro() {
        try {
            String grupo = this.jtf_grupo.getText();
            String grado = this.jtf_grado.getText();
            String id_ciclo = this.jtf_id_ciclo.getText();

            st.executeUpdate("Insert into grupos (grupo,grado,id_ciclo)" + "values ('" + grupo + "','" + grado + "','" + id_ciclo + "');");

            JOptionPane.showMessageDialog(null, "Registro Guardado Exitosamente", "Guardado", JOptionPane.INFORMATION_MESSAGE);

            Conectar();
            botones();
            this.primer_registro();

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "El registro no se ha podido guardar. Rellene correctamente todos los campos", "Error al guardar", JOptionPane.WARNING_MESSAGE);
        }

    }

    private void siguiente_registro() {
        try {
            if (rs.isLast() == false) {
                rs.next();
                this.jtf_id_grupo.setText(rs.getString("id_grupo"));
                this.jtf_grupo.setText(rs.getString("grupo"));
                this.jtf_grado.setText(rs.getString("grado"));
                this.jtf_ciclo.setText(rs.getString("ciclo"));
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }

    private void anterior_registro() {
        try {
            if (rs.isFirst() == false) {
                rs.previous();
                this.jtf_id_grupo.setText(rs.getString("id_grupo"));
                this.jtf_grupo.setText(rs.getString("grupo"));
                this.jtf_grado.setText(rs.getString("grado"));
                this.jtf_ciclo.setText(rs.getString("ciclo"));

            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }

    private void ultimo_registro() {
        try {
            if (rs.isLast() == false) {
                rs.last();
                this.jtf_id_grupo.setText(rs.getString("id_grupo"));
                this.jtf_grupo.setText(rs.getString("grupo"));
                this.jtf_grado.setText(rs.getString("grado"));
                this.jtf_ciclo.setText(rs.getString("ciclo"));

            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }

    private void primer_registro() {
        try {
            if (rs.isFirst() == false) {
                rs.first();
                this.jtf_id_grupo.setText(rs.getString("id_grupo"));
                this.jtf_grupo.setText(rs.getString("grupo"));
                this.jtf_grado.setText(rs.getString("grado"));
                this.jtf_ciclo.setText(rs.getString("ciclo"));
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }

    private void borrar_registro() {
        try {
            String registro = this.jtf_grado.getText();
            st.executeUpdate("delete from grupos where id_grupo=" + this.jtf_id_grupo.getText());
            Conectar();
            JOptionPane.showMessageDialog(null, "Se borro registro del " + registro + " grado", "Eliminado", JOptionPane.WARNING_MESSAGE);

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "No se ha podido borrar el registro debido a que tiene profesores asignados", "Error al borrar", JOptionPane.ERROR_MESSAGE);

        }
    }

    private void tabla() {
        try {
            int seleccion = jt_grupos.getSelectedRow();
            
            jtf_id_grupo.setText(String.valueOf(jt_grupos.getValueAt(seleccion, 0)));            
            jtf_grado.setText(String.valueOf(jt_grupos.getValueAt(seleccion, 1)));
            jtf_grupo.setText(String.valueOf(jt_grupos.getValueAt(seleccion, 2)));
            jtf_ciclo.setText(String.valueOf(jt_grupos.getValueAt(seleccion, 3)));            
            rs = st.executeQuery("SELECT * FROM sistema_gmg.vista_grupos order by grado;");
            jt_grupos.setModel(DbUtils.resultSetToTableModel(rs));
            rs = st.executeQuery("SELECT * FROM vista_grupos;");
            rs.next();
        } catch (SQLException ex) {
            Logger.getLogger(JF_Alumnos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void buscar() {
        try {            
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/sistema_gmg", "root", "1405");

            st = conexion.createStatement();
            
            rs = st.executeQuery("select * from vista_grupos where grado like '%" + this.jtf_buscar.getText() + "%' or  grado like '%" + this.jtf_buscar.getText() + "%';");

            jtf_id_grupo.setText(null);
            jtf_grado.setText(null);
            jtf_grupo.setText(null);
            jtf_ciclo.setText(null);
            
            jt_grupos.setModel(DbUtils.resultSetToTableModel(rs));
            
            jb_cancelar.setEnabled(true);            
            
            rs = st.executeQuery("SELECT * FROM vista_grupos;");
        } catch (SQLException ex) {
            Logger.getLogger(JF_Alumnos.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }

    private void agregar_profesor2() {
        try {
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/sistema_gmg", "root", "1405");
            st = conexion.createStatement();

            st.executeUpdate("insert into relacion_profesor_grupo(id_profesor,id_grupo) values('" + this.jcb_id_extras.getSelectedItem() + "', '" + this.jtf_id_grupo.getText() + "');");
            
            JOptionPane.showMessageDialog(null, "Se asigno profesor al grupo correctamente", "Asignado", JOptionPane.INFORMATION_MESSAGE);
            Conectar();
        } catch (SQLException err) {
            //JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
            JOptionPane.showMessageDialog(null, "El profesor que intenta asignar ya ha sido asignado", "Error al asignar", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void agregar_profesor() {
        try {
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/sistema_gmg", "root", "1405");
            st = conexion.createStatement();

            st.executeUpdate("insert into relacion_profesor_grupo(id_profesor,id_grupo) values('" + this.jcb_id_profe.getSelectedItem() + "', '" + this.jtf_id_grupo.getText() + "');");
            JOptionPane.showMessageDialog(null, "Se asigno profesor al grupo correctamente", "Asignado", JOptionPane.INFORMATION_MESSAGE);
            Conectar();
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "El profesor que intenta asignar ya ha sido asignado", "Error al asignar", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void borrar_asig() {
        try {
            String registro = (String) this.jcb_nombre_profesor.getSelectedItem();
            st.executeUpdate("delete from relacion_profesor_grupo where id_grupo= '" + this.jtf_id_grupo.getText() +",'and id_profesor='" +this.jcb_id_profe.getSelectedItem() + "'; ");
            JOptionPane.showMessageDialog(null, "Se borró la asignacion del profesor " + registro + " correctamente", "Eliminado", JOptionPane.WARNING_MESSAGE);
            Conectar();


        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Este profesor no ha sido asignado a este grupo", "Error al borrar", JOptionPane.ERROR_MESSAGE);

        }
    }
    private void borrar_asig2() {
        try {
            String registro = (String) this.jcb_nombre_profesor.getSelectedItem();
            st.executeUpdate("delete from relacion_profesor_grupo where id_grupo= '" + this.jtf_id_grupo.getText() +",'and id_profesor='" +this.jcb_id_extras.getSelectedItem() + "'; ");
            JOptionPane.showMessageDialog(null, "Se borró la asignacion del profesor " + registro + " correctamente", "Eliminado", JOptionPane.WARNING_MESSAGE);
            Conectar();


        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Este profesor no ha sido asignado a este grupo", "Error al borrar", JOptionPane.ERROR_MESSAGE);

        }
    }
}
