package sistema_gmg;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mike
 */
public class JF_Inscripciones extends javax.swing.JFrame {

    private Connection conexion = null;
    private Statement st;
    private ResultSet rs;
    private TableModel ciclos;

    public void Conectar() {
        try {

            conexion = DriverManager.getConnection("jdbc:mysql://localhost/sistema_gmg", "root", "1405");

            st = conexion.createStatement();

            rs = st.executeQuery("SELECT * FROM sistema_gmg.inscripcion;");
            jt_inscripciones.setModel(DbUtils.resultSetToTableModel(rs));
            rs.next();

            rs = st.executeQuery("SELECT * FROM inscripcion;");
            rs.next();

            this.jtf_id_inscripcion.setText(rs.getString("id_inscripcion"));
            this.jtf_nombre_alum.setText(rs.getString("nombre_alum"));
            this.jtf_ap_paterno_alum.setText(rs.getString("ap_paterno_alum"));
            this.jtf_ap_materno_alum.setText(rs.getString("ap_materno_alum"));
            this.jtf_grado_grupo.setText(rs.getString("grado"));
            this.jtf_ciclo.setText(rs.getString("ciclo"));
            this.jtf_fecha_sh.setText(rs.getString("fecha"));

            jp_nuevo.setVisible(false);
            jb_cancelar.setEnabled(false);
            jb_guardar.setEnabled(false);
            jb_actualizar.setEnabled(false);

            jb_primero.setEnabled(true);
            jb_ultimo.setEnabled(true);
            jb_siguiente.setEnabled(true);
            jb_anterior.setEnabled(true);
            jb_buscar.setEnabled(true);
            jb_borrar.setEnabled(true);
            jb_editar.setEnabled(true);
            jb_nuevo.setEnabled(true);

            jtf_id_ciclo.setVisible(false);
            jtf_id_inscripcion.setVisible(true);
            jtf_id_grupo.setVisible(false);
            jcb_id_grado.setVisible(false);
            jcb_id_alumno.setVisible(false);
            jtf_id_inscripcion.setVisible(false);

            jtf_id_alumno.setVisible(false);
            jtf_nombre_alum.setEditable(false);
            jtf_ap_paterno_alum.setEditable(false);
            jtf_ap_materno_alum.setEditable(false);
            jtf_grado_grupo.setEditable(false);
            jtf_ciclo.setEditable(false);
            jtf_fecha_sh.setEditable(false);

        } catch (SQLException err) {

            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }

    public void combobox() {
        try {
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/sistema_gmg", "root", "1405");

            st = conexion.createStatement();

            rs = st.executeQuery("Select ciclo from ciclos;");
            while (rs.next()) {
                this.jcb_ciclo.addItem(rs.getString("ciclo"));
            }

            rs = st.executeQuery("Select id_alumno,nombre_alum,ap_paterno_alum, ap_materno_alum from alumnos;");
            while (rs.next()) {
                this.jcb_alumno.addItem(rs.getString(2) + " " + rs.getString(3) + " " + rs.getString(4));
                this.jcb_id_alumno.addItem(rs.getString(1));
            }

        } catch (SQLException err) {

            //JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }

    /**
     * Creates new form inscripciones
     */
    public JF_Inscripciones() {
        initComponents();
        combobox();
        Conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_tabla = new javax.swing.JPanel();
        jl_menu = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buttons_2 = new javax.swing.JPanel();
        jb_actualizar = new javax.swing.JButton();
        jb_nuevo = new javax.swing.JButton();
        jb_editar = new javax.swing.JButton();
        jb_guardar = new javax.swing.JButton();
        jb_borrar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jb_regresar = new javax.swing.JButton();
        formulario = new javax.swing.JPanel();
        jl_grado = new javax.swing.JLabel();
        jl_nombre_alum = new javax.swing.JLabel();
        jl_ap_paterno_alum = new javax.swing.JLabel();
        jl_ap_materno_alum = new javax.swing.JLabel();
        jtf_nombre_alum = new javax.swing.JTextField();
        jtf_ap_paterno_alum = new javax.swing.JTextField();
        jtf_ap_materno_alum = new javax.swing.JTextField();
        jtf_grado_grupo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jb_siguiente = new javax.swing.JButton();
        jb_ultimo = new javax.swing.JButton();
        jb_primero = new javax.swing.JButton();
        jb_anterior = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jtf_id_inscripcion = new javax.swing.JTextField();
        jtf_ciclo = new javax.swing.JTextField();
        jtf_fecha_sh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jl_ciclo2 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jb_buscar = new javax.swing.JButton();
        jtf_buscar = new javax.swing.JTextField();
        jp_nuevo = new javax.swing.JPanel();
        jtf_fecha = new javax.swing.JTextField();
        jtf_id_alumno = new javax.swing.JTextField();
        jcb_ciclo = new javax.swing.JComboBox<>();
        jl_ciclo = new javax.swing.JLabel();
        jtf_id_grupo = new javax.swing.JTextField();
        lj_fecha = new javax.swing.JLabel();
        jcb_alumno = new javax.swing.JComboBox<>();
        jcb_grado = new javax.swing.JComboBox<>();
        jl_alumno = new javax.swing.JLabel();
        jcb_id_grado = new javax.swing.JComboBox<>();
        jtf_id_ciclo = new javax.swing.JTextField();
        jl_grupo = new javax.swing.JLabel();
        jcb_id_alumno = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_inscripciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inscripciones");

        panel_tabla.setBackground(new java.awt.Color(10, 34, 64));

        jl_menu.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        jl_menu.setForeground(new java.awt.Color(255, 255, 255));
        jl_menu.setText("Menú");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        buttons_2.setBackground(new java.awt.Color(106, 116, 145));

        jb_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ciclo.png"))); // NOI18N
        jb_actualizar.setText("Actualizar");
        jb_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_actualizarMouseClicked(evt);
            }
        });
        jb_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_actualizarActionPerformed(evt);
            }
        });

        jb_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/new.png"))); // NOI18N
        jb_nuevo.setText("Nuevo");
        jb_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_nuevoMouseClicked(evt);
            }
        });

        jb_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit.png"))); // NOI18N
        jb_editar.setText("Editar");
        jb_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_editarMouseClicked(evt);
            }
        });

        jb_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-Guardar Filled-50.png"))); // NOI18N
        jb_guardar.setText("Guardar");
        jb_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarMouseClicked(evt);
            }
        });
        jb_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_guardarActionPerformed(evt);
            }
        });

        jb_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trash.png"))); // NOI18N
        jb_borrar.setText("Borrar");
        jb_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_borrarMouseClicked(evt);
            }
        });

        jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N
        jb_cancelar.setText("Cancelar");
        jb_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_cancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout buttons_2Layout = new javax.swing.GroupLayout(buttons_2);
        buttons_2.setLayout(buttons_2Layout);
        buttons_2Layout.setHorizontalGroup(
            buttons_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttons_2Layout.createSequentialGroup()
                .addGroup(buttons_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttons_2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jb_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttons_2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jb_cancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(buttons_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buttons_2Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addGroup(buttons_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(buttons_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_borrar)
                            .addComponent(jb_guardar))
                        .addGroup(buttons_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(buttons_2Layout.createSequentialGroup()
                                .addComponent(jb_editar)
                                .addGap(10, 10, 10))
                            .addComponent(jb_nuevo, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addContainerGap(25, Short.MAX_VALUE)))
        );
        buttons_2Layout.setVerticalGroup(
            buttons_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttons_2Layout.createSequentialGroup()
                .addContainerGap(233, Short.MAX_VALUE)
                .addComponent(jb_actualizar)
                .addGap(18, 18, 18)
                .addComponent(jb_cancelar)
                .addGap(37, 37, 37))
            .addGroup(buttons_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buttons_2Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(jb_nuevo)
                    .addGap(18, 18, 18)
                    .addComponent(jb_editar)
                    .addGap(18, 18, 18)
                    .addComponent(jb_guardar)
                    .addGap(18, 18, 18)
                    .addComponent(jb_borrar)
                    .addContainerGap(147, Short.MAX_VALUE)))
        );

        jb_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/home.png"))); // NOI18N
        jb_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_tablaLayout = new javax.swing.GroupLayout(panel_tabla);
        panel_tabla.setLayout(panel_tablaLayout);
        panel_tablaLayout.setHorizontalGroup(
            panel_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_tablaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jl_menu)
                .addGap(124, 124, 124))
            .addGroup(panel_tablaLayout.createSequentialGroup()
                .addGroup(panel_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_tablaLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(buttons_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_tablaLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jb_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_tablaLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        panel_tablaLayout.setVerticalGroup(
            panel_tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_tablaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jb_regresar)
                .addGap(18, 18, 18)
                .addComponent(jl_menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttons_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formulario.setBackground(new java.awt.Color(32, 47, 90));
        formulario.setPreferredSize(new java.awt.Dimension(800, 283));
        formulario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_grado.setForeground(new java.awt.Color(255, 255, 255));
        jl_grado.setText("Grado:");
        formulario.add(jl_grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jl_nombre_alum.setForeground(new java.awt.Color(255, 255, 255));
        jl_nombre_alum.setText("Nombre:");
        formulario.add(jl_nombre_alum, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jl_ap_paterno_alum.setForeground(new java.awt.Color(255, 255, 255));
        jl_ap_paterno_alum.setText("Apellido Paterno:");
        formulario.add(jl_ap_paterno_alum, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 77, -1, -1));

        jl_ap_materno_alum.setForeground(new java.awt.Color(255, 255, 255));
        jl_ap_materno_alum.setText("Apellido Materno:");
        formulario.add(jl_ap_materno_alum, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 134, -1, -1));

        jtf_nombre_alum.setBackground(new java.awt.Color(32, 47, 90));
        jtf_nombre_alum.setForeground(new java.awt.Color(255, 255, 255));
        jtf_nombre_alum.setBorder(null);
        jtf_nombre_alum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_nombre_alumKeyTyped(evt);
            }
        });
        formulario.add(jtf_nombre_alum, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 159, -1));

        jtf_ap_paterno_alum.setBackground(new java.awt.Color(32, 47, 90));
        jtf_ap_paterno_alum.setForeground(new java.awt.Color(255, 255, 255));
        jtf_ap_paterno_alum.setBorder(null);
        jtf_ap_paterno_alum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_ap_paterno_alumKeyTyped(evt);
            }
        });
        formulario.add(jtf_ap_paterno_alum, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 264, -1));

        jtf_ap_materno_alum.setBackground(new java.awt.Color(32, 47, 90));
        jtf_ap_materno_alum.setForeground(new java.awt.Color(255, 255, 255));
        jtf_ap_materno_alum.setBorder(null);
        jtf_ap_materno_alum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_ap_materno_alumKeyTyped(evt);
            }
        });
        formulario.add(jtf_ap_materno_alum, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 176, -1));

        jtf_grado_grupo.setBackground(new java.awt.Color(32, 47, 90));
        jtf_grado_grupo.setForeground(new java.awt.Color(255, 255, 255));
        jtf_grado_grupo.setBorder(null);
        jtf_grado_grupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_grado_grupoKeyTyped(evt);
            }
        });
        formulario.add(jtf_grado_grupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 144, 30));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        formulario.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 104, 219, 18));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        formulario.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 172, 23));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        formulario.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 172, 10));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        formulario.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 179, 13));

        jb_siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-Doble derecha-48.png"))); // NOI18N
        jb_siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_siguienteMouseClicked(evt);
            }
        });
        formulario.add(jb_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 116, -1, -1));

        jb_ultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/derecho.png"))); // NOI18N
        jb_ultimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ultimoMouseClicked(evt);
            }
        });
        jb_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ultimoActionPerformed(evt);
            }
        });
        formulario.add(jb_ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 116, -1, -1));

        jb_primero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-Galón izquierdo-26.png"))); // NOI18N
        jb_primero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_primeroMouseClicked(evt);
            }
        });
        formulario.add(jb_primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 116, -1, -1));

        jb_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-Doble izquierda-48.png"))); // NOI18N
        jb_anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_anteriorMouseClicked(evt);
            }
        });
        formulario.add(jb_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 116, -1, -1));

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Desplazamiento");
        formulario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 46, -1, -1));
        formulario.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 71, 142, 10));

        jtf_id_inscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_id_inscripcionActionPerformed(evt);
            }
        });
        formulario.add(jtf_id_inscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 14, 66, -1));

        jtf_ciclo.setBackground(new java.awt.Color(32, 47, 90));
        jtf_ciclo.setForeground(new java.awt.Color(255, 255, 255));
        jtf_ciclo.setBorder(null);
        jtf_ciclo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_cicloKeyTyped(evt);
            }
        });
        formulario.add(jtf_ciclo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 193, -1));

        jtf_fecha_sh.setBackground(new java.awt.Color(32, 47, 90));
        jtf_fecha_sh.setForeground(new java.awt.Color(255, 255, 255));
        jtf_fecha_sh.setBorder(null);
        formulario.add(jtf_fecha_sh, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 159, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha:");
        formulario.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        jl_ciclo2.setForeground(new java.awt.Color(255, 255, 255));
        jl_ciclo2.setText("Ciclo:");
        formulario.add(jl_ciclo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        formulario.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 179, 20));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        formulario.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 172, 10));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 498));

        jb_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        jb_buscar.setText("Buscar Registro");
        jb_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_buscarMouseClicked(evt);
            }
        });
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed(evt);
            }
        });

        jtf_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_buscarKeyTyped(evt);
            }
        });

        jp_nuevo.setBackground(new java.awt.Color(255, 255, 255));

        jcb_ciclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_cicloActionPerformed(evt);
            }
        });

        jl_ciclo.setText("Ciclo:");

        lj_fecha.setText("Fecha de inscripción:");

        jcb_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_alumnoActionPerformed(evt);
            }
        });

        jcb_grado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_gradoActionPerformed(evt);
            }
        });

        jl_alumno.setText("Alumno:");

        jl_grupo.setText("Grado: y Grupo:");

        javax.swing.GroupLayout jp_nuevoLayout = new javax.swing.GroupLayout(jp_nuevo);
        jp_nuevo.setLayout(jp_nuevoLayout);
        jp_nuevoLayout.setHorizontalGroup(
            jp_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_nuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jp_nuevoLayout.createSequentialGroup()
                            .addComponent(lj_fecha)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtf_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41)
                            .addComponent(jtf_id_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jp_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_nuevoLayout.createSequentialGroup()
                                .addComponent(jl_grupo)
                                .addGap(18, 18, 18)
                                .addComponent(jcb_grado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcb_id_grado, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_nuevoLayout.createSequentialGroup()
                                .addComponent(jl_alumno)
                                .addGap(26, 26, 26)
                                .addComponent(jcb_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcb_id_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jtf_id_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_nuevoLayout.createSequentialGroup()
                        .addComponent(jl_ciclo)
                        .addGap(18, 18, 18)
                        .addComponent(jcb_ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_id_ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jp_nuevoLayout.setVerticalGroup(
            jp_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_nuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_ciclo)
                    .addComponent(jtf_id_ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jp_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_grupo)
                    .addComponent(jcb_grado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_id_grado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jp_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_alumno)
                    .addComponent(jcb_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_id_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jp_nuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lj_fecha)
                    .addComponent(jtf_id_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_id_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jt_inscripciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt_inscripciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_inscripcionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_inscripciones);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jb_buscar)
                .addGap(18, 18, 18)
                .addComponent(jtf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(371, 371, 371))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jp_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_buscar)
                    .addComponent(jtf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jp_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                    .addComponent(formulario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formulario, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane2))
                    .addComponent(panel_tabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_regresarActionPerformed

        JF_Principal principal = new JF_Principal();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jb_regresarActionPerformed

    private void jtf_nombre_alumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_nombre_alumKeyTyped
        char cadena = evt.getKeyChar();
        if (Character.isLowerCase(cadena)) {
            String cad = ("" + cadena).toUpperCase();
            cadena = cad.charAt(0);
            evt.setKeyChar(cadena);
        }
    }//GEN-LAST:event_jtf_nombre_alumKeyTyped

    private void jtf_ap_paterno_alumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_ap_paterno_alumKeyTyped
        char cadena = evt.getKeyChar();
        if (Character.isLowerCase(cadena)) {
            String cad = ("" + cadena).toUpperCase();
            cadena = cad.charAt(0);
            evt.setKeyChar(cadena);
        }
    }//GEN-LAST:event_jtf_ap_paterno_alumKeyTyped

    private void jtf_ap_materno_alumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_ap_materno_alumKeyTyped
        char cadena = evt.getKeyChar();
        if (Character.isLowerCase(cadena)) {
            String cad = ("" + cadena).toUpperCase();
            cadena = cad.charAt(0);
            evt.setKeyChar(cadena);
        }
    }//GEN-LAST:event_jtf_ap_materno_alumKeyTyped

    private void jtf_grado_grupoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_grado_grupoKeyTyped
        char cadena = evt.getKeyChar();
        if (Character.isLowerCase(cadena)) {
            String cad = ("" + cadena).toUpperCase();
            cadena = cad.charAt(0);
            evt.setKeyChar(cadena);
        }
    }//GEN-LAST:event_jtf_grado_grupoKeyTyped

    private void jb_siguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_siguienteMouseClicked
        if (this.jb_siguiente.isEnabled()) {
            siguiente_registro();
        } else {
        }
    }//GEN-LAST:event_jb_siguienteMouseClicked

    private void jb_ultimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ultimoMouseClicked
        if (this.jb_ultimo.isEnabled()) {
            ultimo_registro();
        } else {
        }
    }//GEN-LAST:event_jb_ultimoMouseClicked

    private void jb_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ultimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_ultimoActionPerformed

    private void jb_primeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_primeroMouseClicked
        if (this.jb_primero.isEnabled()) {
            primer_registro();
        } else {
        }
    }//GEN-LAST:event_jb_primeroMouseClicked

    private void jb_anteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_anteriorMouseClicked
        //se tiene que poner a todos los eventos mouse clicked condicion if
        if (this.jb_anterior.isEnabled()) {
            anterior_registro();
        } else {
        }
    }//GEN-LAST:event_jb_anteriorMouseClicked

    private void jtf_id_inscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_id_inscripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_id_inscripcionActionPerformed

    private void jtf_cicloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_cicloKeyTyped
        char cadena = evt.getKeyChar();
        if (Character.isLowerCase(cadena)) {
            String cad = ("" + cadena).toUpperCase();
            cadena = cad.charAt(0);
            evt.setKeyChar(cadena);
        }
    }//GEN-LAST:event_jtf_cicloKeyTyped

    private void jb_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_buscarMouseClicked
        if (this.jb_buscar.isEnabled()) {
            buscar();
        } else {
        }
    }//GEN-LAST:event_jb_buscarMouseClicked

    private void jb_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_buscarActionPerformed

    private void jtf_buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_buscarKeyTyped
        char cadena = evt.getKeyChar();
        if (Character.isLowerCase(cadena)) {
            String cad = ("" + cadena).toUpperCase();
            cadena = cad.charAt(0);
            evt.setKeyChar(cadena);
        }
    }//GEN-LAST:event_jtf_buscarKeyTyped

    private void jcb_cicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_cicloActionPerformed
        try {
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/sistema_gmg", "root", "1405");
            st = conexion.createStatement();

            ResultSet rs = st.executeQuery("select id_ciclo from ciclos where ciclo = '" + this.jcb_ciclo.getSelectedItem() + "'");
            rs.next();
            this.jtf_id_ciclo.setText(String.valueOf(rs.getString("id_ciclo")));

            this.jcb_grado.removeAllItems();
            this.jcb_id_grado.removeAllItems();
            rs = st.executeQuery("Select id_grupo,grado,grupo from grupos where id_ciclo = '" + this.jtf_id_ciclo.getText() + "';");
            while (rs.next()) {
                this.jcb_grado.addItem(rs.getString(2) + " - " + rs.getString(3));
                this.jcb_id_grado.addItem(rs.getString(1));
            }

        } catch (Exception e) {
            // JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jcb_cicloActionPerformed

    private void jcb_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_alumnoActionPerformed
        try {
            int index = this.jcb_alumno.getSelectedIndex();
            this.jtf_id_alumno.setText("" + index);
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/sistema_gmg", "root", "1405");
            st = conexion.createStatement();
            this.jcb_id_alumno.setSelectedIndex(index);

        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jcb_alumnoActionPerformed

    private void jcb_gradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_gradoActionPerformed
        try {
            int index = this.jcb_grado.getSelectedIndex();
            this.jtf_id_grupo.setText("" + index);
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/sistema_gmg", "root", "1405");
            st = conexion.createStatement();
            this.jcb_id_grado.setSelectedIndex(index);

        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jcb_gradoActionPerformed

    private void jb_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_actualizarMouseClicked
        if (this.jb_actualizar.isEnabled()) {
            String registro = null;
            int alerta = JOptionPane.showConfirmDialog(null, "¿Quiere actualizar el " + registro + " grado?", "Actualizar", JOptionPane.WARNING_MESSAGE, JOptionPane.INFORMATION_MESSAGE);
            if (JOptionPane.OK_OPTION == alerta) {
                JOptionPane.showMessageDialog(null, "Se actualizó el " + registro + " grado exitosamente", "Actualizado", JOptionPane.INFORMATION_MESSAGE);
                actualizar_registro();

            } else {

            }
        } else {
        }
    }//GEN-LAST:event_jb_actualizarMouseClicked

    private void jb_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_actualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_actualizarActionPerformed

    private void jb_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_nuevoMouseClicked
        if (this.jb_nuevo.isEnabled()) {
            nuevo_registro();
            jp_nuevo.setVisible(true);
        } else {
        }
    }//GEN-LAST:event_jb_nuevoMouseClicked

    private void jb_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_editarMouseClicked
        if (this.jb_editar.isEnabled()) {

            jb_primero.setEnabled(false);
            jb_ultimo.setEnabled(false);
            jb_siguiente.setEnabled(false);
            jb_anterior.setEnabled(false);
            jb_buscar.setEnabled(false);
            jb_borrar.setEnabled(false);
            jb_actualizar.setEnabled(true);
            jb_cancelar.setEnabled(true);
            jb_guardar.setEnabled(false);
            jb_nuevo.setEnabled(false);

            jp_nuevo.setVisible(true);
        } else {
        }
    }//GEN-LAST:event_jb_editarMouseClicked

    private void jb_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarMouseClicked
        if (this.jb_guardar.isEnabled()) {
            guardar_registro();
        } else {
        }
    }//GEN-LAST:event_jb_guardarMouseClicked

    private void jb_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_guardarActionPerformed

    private void jb_borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_borrarMouseClicked
        if (this.jb_borrar.isEnabled()) {
            String registro = this.jtf_nombre_alum.getText();

            int alerta = JOptionPane.showConfirmDialog(null, "¿Quiere eliminar la inscripcion del alumno " + registro +"" , "Se borrarrá el registro", JOptionPane.WARNING_MESSAGE, JOptionPane.ERROR_MESSAGE);

            if (JOptionPane.OK_OPTION == alerta) {
                borrar_registro();

            } else {

            }
        } else {
        }
    }//GEN-LAST:event_jb_borrarMouseClicked

    private void jb_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_cancelarMouseClicked
        if (this.jb_cancelar.isEnabled()) {
            Conectar();
        } else {
        }
    }//GEN-LAST:event_jb_cancelarMouseClicked

    private void jt_inscripcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_inscripcionesMouseClicked

        tabla();

    }//GEN-LAST:event_jt_inscripcionesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Inscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Inscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Inscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Inscripciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Inscripciones().setVisible(true);
            }
        });
    }

    private void nuevo_registro() {

        jb_nuevo.setEnabled(false);
        jb_primero.setEnabled(false);
        jb_ultimo.setEnabled(false);
        jb_siguiente.setEnabled(false);
        jb_anterior.setEnabled(false);
        jb_buscar.setEnabled(false);
        jb_borrar.setEnabled(false);
        jb_actualizar.setEnabled(false);
        jb_cancelar.setEnabled(true);
        jb_guardar.setEnabled(true);
        jb_editar.setEnabled(false);

        jtf_fecha.setText(null);

        jtf_nombre_alum.setText(null);
        jtf_ap_paterno_alum.setText(null);
        jtf_ap_materno_alum.setText(null);
        jtf_grado_grupo.setText(null);
        jtf_ciclo.setText(null);
        jtf_fecha_sh.setText(null);
    }

    private void actualizar_registro() {
        try {
            jtf_fecha.getText();
            jcb_ciclo.getSelectedItem();
            jcb_grado.getSelectedItem();
            jcb_alumno.getSelectedItem();

            st.executeUpdate("update inscripciones set id_alumno= '" + jcb_id_alumno.getSelectedItem()
                    + "',id_grupo= '" + jcb_id_grado.getSelectedItem() + "' where id_inscripcion= '" + this.jtf_id_inscripcion.getText() + "'");

            Conectar();
            this.primer_registro();

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Rellene correctamente los campos", "Error al actualizar", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void guardar_registro() {
        try {

            String id_ciclo = this.jtf_id_ciclo.getText();
            String id_grado = (String) this.jcb_id_grado.getSelectedItem();
            String id_alumno = (String) this.jcb_id_alumno.getSelectedItem();
            String fecha = this.jtf_fecha.getText();

            st.executeUpdate("Insert into inscripciones (id_alumno,id_grupo,fecha)" + "values ('" + id_alumno + "','" + id_grado + "','" + fecha + "');");

            Conectar();
            this.primer_registro();

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Rellene correctamente los campos", "Error al guardar", JOptionPane.INFORMATION_MESSAGE);
        }

    }

    private void siguiente_registro() {
        try {
            if (rs.isLast() == false) {
                rs.next();

                this.jtf_id_inscripcion.setText(rs.getString("id_inscripcion"));
                this.jtf_nombre_alum.setText(rs.getString("nombre_alum"));
                this.jtf_ap_paterno_alum.setText(rs.getString("ap_paterno_alum"));
                this.jtf_ap_materno_alum.setText(rs.getString("ap_materno_alum"));
                this.jtf_grado_grupo.setText(rs.getString("grado"));
                this.jtf_ciclo.setText(rs.getString("ciclo"));
                this.jtf_fecha_sh.setText(rs.getString("fecha"));

            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }

    private void anterior_registro() {
        try {
            if (rs.isFirst() == false) {
                rs.previous();

                this.jtf_id_inscripcion.setText(rs.getString("id_inscripcion"));
                this.jtf_nombre_alum.setText(rs.getString("nombre_alum"));
                this.jtf_ap_paterno_alum.setText(rs.getString("ap_paterno_alum"));
                this.jtf_ap_materno_alum.setText(rs.getString("ap_materno_alum"));
                this.jtf_grado_grupo.setText(rs.getString("grado"));
                this.jtf_ciclo.setText(rs.getString("ciclo"));
                this.jtf_fecha_sh.setText(rs.getString("fecha"));

            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }

    private void ultimo_registro() {
        try {
            if (rs.isLast() == false) {
                rs.last();

                this.jtf_id_inscripcion.setText(rs.getString("id_inscripcion"));
                this.jtf_nombre_alum.setText(rs.getString("nombre_alum"));
                this.jtf_ap_paterno_alum.setText(rs.getString("ap_paterno_alum"));
                this.jtf_ap_materno_alum.setText(rs.getString("ap_materno_alum"));
                this.jtf_grado_grupo.setText(rs.getString("grado"));
                this.jtf_ciclo.setText(rs.getString("ciclo"));
                this.jtf_fecha_sh.setText(rs.getString("fecha"));

            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }

    private void primer_registro() {
        try {
            if (rs.isFirst() == false) {
                rs.first();

                this.jtf_id_inscripcion.setText(rs.getString("id_inscripcion"));
                this.jtf_nombre_alum.setText(rs.getString("nombre_alum"));
                this.jtf_ap_paterno_alum.setText(rs.getString("ap_paterno_alum"));
                this.jtf_ap_materno_alum.setText(rs.getString("ap_materno_alum"));
                this.jtf_grado_grupo.setText(rs.getString("grado"));
                this.jtf_ciclo.setText(rs.getString("ciclo"));
                this.jtf_fecha_sh.setText(rs.getString("fecha"));

            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }

    private void borrar_registro() {
        try {
            st.executeUpdate("delete from inscripciones where id_inscripcion=" + this.jtf_id_inscripcion.getText());
            Conectar();
            this.primer_registro();

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());

        }
    }

    private void buscar() {
        try {
            rs = st.executeQuery("select * from sistema_gmg.inscripcion where nombre_alum like '" + this.jtf_buscar.getText() + "%'");

            jt_inscripciones.setModel(DbUtils.resultSetToTableModel(rs));

            jb_cancelar.setEnabled(true);
            rs = st.executeQuery("select *from sistema_gmg.inscripcion");
        } catch (SQLException ex) {
            Logger.getLogger(JF_Alumnos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttons_2;
    private javax.swing.JPanel formulario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JButton jb_actualizar;
    private javax.swing.JButton jb_anterior;
    private javax.swing.JButton jb_borrar;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_editar;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_nuevo;
    private javax.swing.JButton jb_primero;
    private javax.swing.JButton jb_regresar;
    private javax.swing.JButton jb_siguiente;
    private javax.swing.JButton jb_ultimo;
    private javax.swing.JComboBox<String> jcb_alumno;
    private javax.swing.JComboBox<String> jcb_ciclo;
    private javax.swing.JComboBox<String> jcb_grado;
    private javax.swing.JComboBox<String> jcb_id_alumno;
    private javax.swing.JComboBox<String> jcb_id_grado;
    private javax.swing.JLabel jl_alumno;
    private javax.swing.JLabel jl_ap_materno_alum;
    private javax.swing.JLabel jl_ap_paterno_alum;
    private javax.swing.JLabel jl_ciclo;
    private javax.swing.JLabel jl_ciclo2;
    private javax.swing.JLabel jl_grado;
    private javax.swing.JLabel jl_grupo;
    private javax.swing.JLabel jl_menu;
    private javax.swing.JLabel jl_nombre_alum;
    private javax.swing.JPanel jp_nuevo;
    private javax.swing.JTable jt_inscripciones;
    private javax.swing.JTextField jtf_ap_materno_alum;
    private javax.swing.JTextField jtf_ap_paterno_alum;
    private javax.swing.JTextField jtf_buscar;
    private javax.swing.JTextField jtf_ciclo;
    private javax.swing.JTextField jtf_fecha;
    private javax.swing.JTextField jtf_fecha_sh;
    private javax.swing.JTextField jtf_grado_grupo;
    private javax.swing.JTextField jtf_id_alumno;
    private javax.swing.JTextField jtf_id_ciclo;
    private javax.swing.JTextField jtf_id_grupo;
    private javax.swing.JTextField jtf_id_inscripcion;
    private javax.swing.JTextField jtf_nombre_alum;
    private javax.swing.JLabel lj_fecha;
    private javax.swing.JPanel panel_tabla;
    // End of variables declaration//GEN-END:variables

    private void tabla() {
        try {
            int seleccion = jt_inscripciones.getSelectedRow();

            jtf_id_inscripcion.setText(String.valueOf(jt_inscripciones.getValueAt(seleccion, 0)));
            jtf_nombre_alum.setText(String.valueOf(jt_inscripciones.getValueAt(seleccion, 1)));
            jtf_ap_paterno_alum.setText(String.valueOf(jt_inscripciones.getValueAt(seleccion, 2)));
            jtf_ap_materno_alum.setText(String.valueOf(jt_inscripciones.getValueAt(seleccion, 3)));
            jtf_grado_grupo.setText(String.valueOf(jt_inscripciones.getValueAt(seleccion, 4)));
            jtf_ciclo.setText(String.valueOf(jt_inscripciones.getValueAt(seleccion, 5)));
            jtf_fecha_sh.setText(String.valueOf(jt_inscripciones.getValueAt(seleccion, 6)));

            rs = st.executeQuery("SELECT * FROM inscripcion;");
            jt_inscripciones.setModel(DbUtils.resultSetToTableModel(rs));
            rs = st.executeQuery("SELECT * FROM inscripcion;");
        } catch (SQLException ex) {
            Logger.getLogger(JF_Alumnos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
