/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_gmg;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mike
 */
public class JF_Login extends javax.swing.JFrame {
    
    private Connection conexion = null;
    private Statement st;
    private ResultSet rs;
    
     public void Conectar() {
        try {

            conexion = DriverManager.getConnection("jdbc:mysql://localhost/sistema_gmg", "root", "1405");

            st = conexion.createStatement();            

        } catch (SQLException err) {

            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }
     
    private void access(){    
        try {
            rs = st.executeQuery("select count(usuario) from login where usuario='"+ this.jtf_usuario.getText()
                    + "' and password='" + this.jpf_password.getText() +"';");
            int res = 0;
            
            if(rs.first()==true)
                
                res = (rs.getInt(1));
            if(res == 1){
                JOptionPane.showMessageDialog(null,"Bienvenido al sistema!","Acceso Validado",JOptionPane.INFORMATION_MESSAGE);
                JF_Principal principal = new JF_Principal();
                principal.setVisible(true);
                dispose();
            }
            else{
                JOptionPane.showMessageDialog(null,"Por favor revisa que tus datos sean correctos","Acceso No Concedido",JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(JF_Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    

    /**
     * Creates new form login
     */
    public JF_Login() {
        initComponents();
        Conectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        contenedor2 = new javax.swing.JPanel();
        jl_usuario = new javax.swing.JLabel();
        jtf_usuario = new javax.swing.JTextField();
        jl_password = new javax.swing.JLabel();
        jpf_password = new javax.swing.JPasswordField();
        jb_entrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Iniciar Sesión");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(790, 505));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedor1.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo.jpg"))); // NOI18N

        javax.swing.GroupLayout contenedor1Layout = new javax.swing.GroupLayout(contenedor1);
        contenedor1.setLayout(contenedor1Layout);
        contenedor1Layout.setHorizontalGroup(
            contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedor1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(logo)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        contenedor1Layout.setVerticalGroup(
            contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedor1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(logo)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(contenedor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        contenedor2.setBackground(new java.awt.Color(10, 34, 64));
        contenedor2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_usuario.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        jl_usuario.setText("Usuario:");
        contenedor2.add(jl_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 70, 21));

        jtf_usuario.setBackground(new java.awt.Color(10, 34, 64));
        jtf_usuario.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        jtf_usuario.setForeground(new java.awt.Color(255, 255, 255));
        jtf_usuario.setBorder(null);
        jtf_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_usuarioActionPerformed(evt);
            }
        });
        contenedor2.add(jtf_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 240, 20));

        jl_password.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jl_password.setForeground(new java.awt.Color(255, 255, 255));
        jl_password.setText("Contraseña:");
        contenedor2.add(jl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jpf_password.setBackground(new java.awt.Color(10, 34, 64));
        jpf_password.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        jpf_password.setForeground(new java.awt.Color(255, 255, 255));
        jpf_password.setBorder(null);
        jpf_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpf_passwordActionPerformed(evt);
            }
        });
        contenedor2.add(jpf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 240, 20));

        jb_entrar.setText("Entrar");
        jb_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_entrarMouseClicked(evt);
            }
        });
        jb_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_entrarActionPerformed(evt);
            }
        });
        contenedor2.add(jb_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 130, 50));
        contenedor2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 240, 20));
        contenedor2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 192, 240, 20));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inicia sesión en el sistema");
        contenedor2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        getContentPane().add(contenedor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 390, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_usuarioActionPerformed

    private void jb_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_entrarActionPerformed
        access();
    }//GEN-LAST:event_jb_entrarActionPerformed

    private void jb_entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_entrarMouseClicked
        access();
    }//GEN-LAST:event_jb_entrarMouseClicked

    private void jpf_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpf_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpf_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedor1;
    private javax.swing.JPanel contenedor2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jb_entrar;
    private javax.swing.JLabel jl_password;
    private javax.swing.JLabel jl_usuario;
    private javax.swing.JPasswordField jpf_password;
    private javax.swing.JTextField jtf_usuario;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
