/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_gmg;

/**
 *
 * @author Mike
 */
public class JF_Principal extends javax.swing.JFrame {
    
    /**
     * Creates new form principal
     */
    public JF_Principal() {        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor1 = new javax.swing.JPanel();
        salir = new javax.swing.JLabel();
        contenedor2 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jtf_tipo_usuario = new javax.swing.JTextField();
        slogan = new javax.swing.JLabel();
        contenedor3 = new javax.swing.JPanel();
        jb_ciclos = new javax.swing.JButton();
        jb_alumnos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jb_profesores = new javax.swing.JButton();
        jb_materias = new javax.swing.JButton();
        jb_tutores = new javax.swing.JButton();
        jb_inscripciones = new javax.swing.JButton();
        jb_periodos = new javax.swing.JButton();
        jb_grupos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ventana Principal");
        setPreferredSize(new java.awt.Dimension(885, 428));
        setResizable(false);

        contenedor1.setBackground(new java.awt.Color(20, 69, 130));
        contenedor1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-Cierre de sesión redondeado Filled-50.png"))); // NOI18N
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        contenedor1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        contenedor2.setBackground(new java.awt.Color(255, 255, 255));
        contenedor2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Century Schoolbook L", 0, 36)); // NOI18N
        titulo.setText("Sistema gestor de escuelas V1.0");
        contenedor2.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 50));

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-Usuario-48.png"))); // NOI18N
        contenedor2.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setPreferredSize(new java.awt.Dimension(60, 10));
        contenedor2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 130, 10));

        jtf_tipo_usuario.setBorder(null);
        contenedor2.add(jtf_tipo_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 130, -1));

        slogan.setText("Por un mejor control de sus hijos");
        contenedor2.add(slogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        contenedor3.setBackground(new java.awt.Color(10, 34, 64));
        contenedor3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_ciclos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ciclo.png"))); // NOI18N
        jb_ciclos.setText("Ciclos");
        jb_ciclos.setFocusable(false);
        jb_ciclos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_ciclos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jb_ciclos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ciclosActionPerformed(evt);
            }
        });
        contenedor3.add(jb_ciclos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, -1));

        jb_alumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/student-icon-17870.png"))); // NOI18N
        jb_alumnos.setText("Alumnos");
        jb_alumnos.setFocusable(false);
        jb_alumnos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_alumnos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jb_alumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_alumnosActionPerformed(evt);
            }
        });
        contenedor3.add(jb_alumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Selecciona interfaz a trabajar");
        contenedor3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jb_profesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/profesor.png"))); // NOI18N
        jb_profesores.setText("Profesores");
        jb_profesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_profesoresActionPerformed(evt);
            }
        });
        contenedor3.add(jb_profesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 130, -1));

        jb_materias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/materias.jpg"))); // NOI18N
        jb_materias.setText("Materias");
        jb_materias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_materiasActionPerformed(evt);
            }
        });
        contenedor3.add(jb_materias, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        jb_tutores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tutor.png"))); // NOI18N
        jb_tutores.setText("Tutores");
        jb_tutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_tutoresActionPerformed(evt);
            }
        });
        contenedor3.add(jb_tutores, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jb_inscripciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ins.png"))); // NOI18N
        jb_inscripciones.setText("Inscripciones");
        jb_inscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_inscripcionesActionPerformed(evt);
            }
        });
        contenedor3.add(jb_inscripciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jb_periodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/per.png"))); // NOI18N
        jb_periodos.setText("Periodo de calificaciones");
        jb_periodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_periodosActionPerformed(evt);
            }
        });
        contenedor3.add(jb_periodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        jb_grupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/grupos.jpg"))); // NOI18N
        jb_grupos.setText("Grupos");
        jb_grupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_gruposActionPerformed(evt);
            }
        });
        contenedor3.add(jb_grupos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenedor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contenedor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenedor2, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedor3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(contenedor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_alumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_alumnosActionPerformed
        
        JF_Alumnos alumnos = new JF_Alumnos();
        alumnos.setVisible(true);        
        dispose();
    }//GEN-LAST:event_jb_alumnosActionPerformed

    private void jb_ciclosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ciclosActionPerformed
        
        JF_Ciclos ciclos = new JF_Ciclos();
        ciclos.setVisible(true);
        dispose();
    }//GEN-LAST:event_jb_ciclosActionPerformed

    private void jb_gruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_gruposActionPerformed
        JF_Grupos grupos = new JF_Grupos();
        grupos.setVisible(true);
        dispose();
    }//GEN-LAST:event_jb_gruposActionPerformed

    private void jb_tutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_tutoresActionPerformed
        JF_Tutores tutores = new JF_Tutores();
        tutores.setVisible(true);
        dispose();
    }//GEN-LAST:event_jb_tutoresActionPerformed

    private void jb_profesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_profesoresActionPerformed
        
        JF_Profesores profesores = new JF_Profesores();
        profesores.setVisible(true);
        dispose();
    }//GEN-LAST:event_jb_profesoresActionPerformed

    private void jb_materiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_materiasActionPerformed
        
        JF_Materias materias = new JF_Materias();
        materias.setVisible(true);
        dispose();
    }//GEN-LAST:event_jb_materiasActionPerformed

    private void jb_inscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_inscripcionesActionPerformed
        
        JF_Inscripciones inscripciones = new JF_Inscripciones();
        inscripciones.setVisible(true);
        dispose();
    }//GEN-LAST:event_jb_inscripcionesActionPerformed

    private void jb_periodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_periodosActionPerformed
        
        JF_Periodo_calificaciones periodo_calificaciones = new JF_Periodo_calificaciones();
        periodo_calificaciones.setVisible(true);
        dispose();
    }//GEN-LAST:event_jb_periodosActionPerformed

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedor1;
    private javax.swing.JPanel contenedor2;
    private javax.swing.JPanel contenedor3;
    private javax.swing.JLabel icono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jb_alumnos;
    private javax.swing.JButton jb_ciclos;
    private javax.swing.JButton jb_grupos;
    private javax.swing.JButton jb_inscripciones;
    private javax.swing.JButton jb_materias;
    private javax.swing.JButton jb_periodos;
    private javax.swing.JButton jb_profesores;
    private javax.swing.JButton jb_tutores;
    private javax.swing.JTextField jtf_tipo_usuario;
    private javax.swing.JLabel salir;
    private javax.swing.JLabel slogan;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
