/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_gmg;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.*;
import net.proteanit.sql.DbUtils;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author esmeralda
 */
public class JF_Tutores extends javax.swing.JFrame {

    private Connection conexion;
    private Statement st;
    private ResultSet rs;

    /**
     * Creates new form Tutores
     */
    public void Conectar() {
        try {
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/sistema_gmg", "root", "1405");
            st = conexion.createStatement();
            
            rs = st.executeQuery("select * from sistema_gmg.padre_alumno;");
            jt_relacion.setModel(DbUtils.resultSetToTableModel(rs));
            rs.next();
            
            rs = st.executeQuery("select * from tutor");
            jt_tutor.setModel(DbUtils.resultSetToTableModel(rs));
            rs.next();
            
            rs = st.executeQuery("Select * from tutor");
            rs.next();

            this.jtf_id_tutor.setText(rs.getString("id_tutor"));
            this.jtf_nombre_tutor.setText(rs.getString("nombre_tutor"));
            this.jtf_apellido_paterno_tut.setText(rs.getString("apellido_paterno_tut"));
            this.jtf_apellido_materno_tut.setText(rs.getString("apellido_materno_tut"));
            this.jtf_calle.setText(rs.getString("calle"));
            this.jtf_colonia.setText(rs.getString("colonia"));
            this.jtf_no_casa.setText(rs.getString("no_casa"));
            this.jtf_codigo_postal.setText(rs.getString("codigo_postal"));
            this.jtf_tel_casa.setText(rs.getString("tel_casa"));
            this.jtf_tel_celular.setText(rs.getString("tel_celular"));
            this.jtf_tel_emergencia.setText(rs.getString("tel_emergencia"));
                        
            jb_cancelar.setEnabled(false);
            jb_guardar.setEnabled(false);
            jb_actualizar.setEnabled(false);

            jb_primero.setEnabled(true);
            jb_ultimo.setEnabled(true);
            jb_siguiente.setEnabled(true);
            jb_anterior.setEnabled(true);
            jb_buscar.setEnabled(true);
            jb_borrar.setEnabled(true);
            jb_editar.setEnabled(true);
            jb_nuevo.setEnabled(true);
            
            jp_hijos.setVisible(false);
            jtf_id_tutor.setVisible(true);
            jtf_id_alumno.setVisible(false);
            jcb_id_alumno.setVisible(false);
            jtf_nombre_tutor.setEditable(false);
            jtf_apellido_paterno_tut.setEditable(false);
            jtf_apellido_materno_tut.setEditable(false);
            jtf_calle.setEditable(false);
            jtf_colonia.setEditable(false);
            jtf_codigo_postal.setEditable(false);
            jtf_tel_casa.setEditable(false);
            jtf_tel_celular.setEditable(false);
            jtf_tel_emergencia.setEditable(false);
            jtf_no_casa.setEditable(false);
                       
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }

    }
    
        public void combobox(){
            try {
                conexion = DriverManager.getConnection("jdbc:mysql://localhost/sistema_gmg", "root", "1405");              
                st = conexion.createStatement();
                
                rs = st.executeQuery("Select id_alumno,nombre_alum,ap_paterno_alum, ap_materno_alum from alumnos;");
            while (rs.next()) {
                this.jcb_alumno.addItem(rs.getString(2) + " " + rs.getString(3) + " " + rs.getString(4));
                this.jcb_id_alumno.addItem(rs.getString(1));
            }
            
            } catch (SQLException err) {

                JOptionPane.showMessageDialog(null, "Error " + err.getMessage());

            } 
        }

    public JF_Tutores()  {
        initComponents();
        combobox();
        AutoCompleteDecorator.decorate(jcb_alumno);
        Conectar();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jb_siguiente = new javax.swing.JButton();
        jb_ultimo = new javax.swing.JButton();
        jb_primero = new javax.swing.JButton();
        jb_anterior = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jtf_id_tutor = new javax.swing.JTextField();
        jtf_no_casa = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        jtf_codigo_postal = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        jtf_tel_emergencia = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        jtf_tel_casa = new javax.swing.JTextField();
        jSeparator21 = new javax.swing.JSeparator();
        jtf_tel_celular = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        jl_nombre_tutor = new javax.swing.JLabel();
        jl_ap_paterno_tut = new javax.swing.JLabel();
        jtf_nombre_tutor = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        jl_ap_materno_tut = new javax.swing.JLabel();
        jl_calle = new javax.swing.JLabel();
        jl_colonia = new javax.swing.JLabel();
        jl_no_casa = new javax.swing.JLabel();
        jl_codigo_postal = new javax.swing.JLabel();
        jl_tel_alternativo = new javax.swing.JLabel();
        jl_tel_casa = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jl_tel_celular = new javax.swing.JLabel();
        jtf_apellido_paterno_tut = new javax.swing.JTextField();
        jtf_apellido_materno_tut = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jtf_calle = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jtf_colonia = new javax.swing.JTextField();
        panel_tabla = new javax.swing.JPanel();
        jl_menu = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buttons_2 = new javax.swing.JPanel();
        jb_guardar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jb_actualizar = new javax.swing.JButton();
        jb_borrar = new javax.swing.JButton();
        jb_editar = new javax.swing.JButton();
        jb_nuevo = new javax.swing.JButton();
        jb_asignar = new javax.swing.JButton();
        jb_regresar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jb_buscar = new javax.swing.JButton();
        jtf_buscar = new javax.swing.JTextField();
        jp_hijos = new javax.swing.JPanel();
        jb_agregar = new javax.swing.JButton();
        jcb_alumno = new javax.swing.JComboBox<>();
        jcb_id_alumno = new javax.swing.JComboBox<>();
        jtf_id_alumno = new javax.swing.JTextField();
        jb_quitar = new javax.swing.JButton();
        jl_alumno = new javax.swing.JLabel();
        jl_alumnos = new javax.swing.JLabel();
        jt_tutores = new javax.swing.JScrollPane();
        jt_tutor = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_relacion = new javax.swing.JTable();
        jl_hijos = new javax.swing.JLabel();
        jl_tutores = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tutores");

        jPanel2.setBackground(new java.awt.Color(32, 47, 90));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-Doble derecha-48.png"))); // NOI18N
        jb_siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_siguienteMouseClicked(evt);
            }
        });
        jPanel2.add(jb_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, -1, -1));

        jb_ultimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/derecho.png"))); // NOI18N
        jb_ultimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_ultimoMouseClicked(evt);
            }
        });
        jb_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ultimoActionPerformed(evt);
            }
        });
        jPanel2.add(jb_ultimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, -1, -1));

        jb_primero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-Galón izquierdo-26.png"))); // NOI18N
        jb_primero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_primeroMouseClicked(evt);
            }
        });
        jPanel2.add(jb_primero, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        jb_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-Doble izquierda-48.png"))); // NOI18N
        jb_anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_anteriorMouseClicked(evt);
            }
        });
        jPanel2.add(jb_anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Desplazamiento");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));
        jPanel2.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 142, 10));
        jPanel2.add(jtf_id_tutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, -1));

        jtf_no_casa.setBackground(new java.awt.Color(32, 47, 90));
        jtf_no_casa.setForeground(new java.awt.Color(255, 255, 255));
        jtf_no_casa.setBorder(null);
        jPanel2.add(jtf_no_casa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 150, 20));
        jPanel2.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 180, 10));

        jtf_codigo_postal.setBackground(new java.awt.Color(32, 47, 90));
        jtf_codigo_postal.setForeground(new java.awt.Color(255, 255, 255));
        jtf_codigo_postal.setBorder(null);
        jPanel2.add(jtf_codigo_postal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 110, 20));
        jPanel2.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 142, 10));

        jtf_tel_emergencia.setBackground(new java.awt.Color(32, 47, 90));
        jtf_tel_emergencia.setForeground(new java.awt.Color(255, 255, 255));
        jtf_tel_emergencia.setBorder(null);
        jPanel2.add(jtf_tel_emergencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 150, 20));
        jPanel2.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 170, 10));

        jtf_tel_casa.setBackground(new java.awt.Color(32, 47, 90));
        jtf_tel_casa.setForeground(new java.awt.Color(255, 255, 255));
        jtf_tel_casa.setBorder(null);
        jPanel2.add(jtf_tel_casa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 120, 20));
        jPanel2.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 142, 10));

        jtf_tel_celular.setBackground(new java.awt.Color(32, 47, 90));
        jtf_tel_celular.setForeground(new java.awt.Color(255, 255, 255));
        jtf_tel_celular.setBorder(null);
        jPanel2.add(jtf_tel_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 120, 20));
        jPanel2.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 142, 10));

        jl_nombre_tutor.setForeground(new java.awt.Color(255, 255, 255));
        jl_nombre_tutor.setText("Nombre:");
        jPanel2.add(jl_nombre_tutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jl_ap_paterno_tut.setForeground(new java.awt.Color(255, 255, 255));
        jl_ap_paterno_tut.setText("Apellido Paterno:");
        jPanel2.add(jl_ap_paterno_tut, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jtf_nombre_tutor.setBackground(new java.awt.Color(32, 47, 90));
        jtf_nombre_tutor.setForeground(new java.awt.Color(255, 255, 255));
        jtf_nombre_tutor.setBorder(null);
        jtf_nombre_tutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nombre_tutorActionPerformed(evt);
            }
        });
        jPanel2.add(jtf_nombre_tutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 120, 20));
        jPanel2.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 142, 10));

        jl_ap_materno_tut.setForeground(new java.awt.Color(255, 255, 255));
        jl_ap_materno_tut.setText("Apellido Materno:");
        jPanel2.add(jl_ap_materno_tut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 20));

        jl_calle.setForeground(new java.awt.Color(255, 255, 255));
        jl_calle.setText("Calle:");
        jPanel2.add(jl_calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jl_colonia.setForeground(new java.awt.Color(255, 255, 255));
        jl_colonia.setText("Colonia:");
        jPanel2.add(jl_colonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jl_no_casa.setForeground(new java.awt.Color(255, 255, 255));
        jl_no_casa.setText("No. Casa:");
        jPanel2.add(jl_no_casa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jl_codigo_postal.setForeground(new java.awt.Color(255, 255, 255));
        jl_codigo_postal.setText("Codigo Postal:");
        jPanel2.add(jl_codigo_postal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jl_tel_alternativo.setForeground(new java.awt.Color(255, 255, 255));
        jl_tel_alternativo.setText("Tel. Emergencia:");
        jPanel2.add(jl_tel_alternativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jl_tel_casa.setForeground(new java.awt.Color(255, 255, 255));
        jl_tel_casa.setText("Tel. Casa:");
        jPanel2.add(jl_tel_casa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));
        jPanel2.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 142, 10));

        jl_tel_celular.setForeground(new java.awt.Color(255, 255, 255));
        jl_tel_celular.setText("Tel. Celular:");
        jPanel2.add(jl_tel_celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jtf_apellido_paterno_tut.setBackground(new java.awt.Color(32, 47, 90));
        jtf_apellido_paterno_tut.setForeground(new java.awt.Color(255, 255, 255));
        jtf_apellido_paterno_tut.setBorder(null);
        jPanel2.add(jtf_apellido_paterno_tut, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 130, 20));

        jtf_apellido_materno_tut.setBackground(new java.awt.Color(32, 47, 90));
        jtf_apellido_materno_tut.setForeground(new java.awt.Color(255, 255, 255));
        jtf_apellido_materno_tut.setBorder(null);
        jPanel2.add(jtf_apellido_materno_tut, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 130, 20));
        jPanel2.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 160, 10));

        jtf_calle.setBackground(new java.awt.Color(32, 47, 90));
        jtf_calle.setForeground(new java.awt.Color(255, 255, 255));
        jtf_calle.setBorder(null);
        jPanel2.add(jtf_calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 190, 20));
        jPanel2.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 220, 10));
        jPanel2.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 220, 10));

        jtf_colonia.setBackground(new java.awt.Color(32, 47, 90));
        jtf_colonia.setForeground(new java.awt.Color(255, 255, 255));
        jtf_colonia.setBorder(null);
        jPanel2.add(jtf_colonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 200, 20));

        panel_tabla.setBackground(new java.awt.Color(10, 34, 64));
        panel_tabla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_menu.setFont(new java.awt.Font("Comfortaa", 0, 18)); // NOI18N
        jl_menu.setForeground(new java.awt.Color(255, 255, 255));
        jl_menu.setText("Menú");
        panel_tabla.add(jl_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 86, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        panel_tabla.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 113, 80, 18));

        buttons_2.setBackground(new java.awt.Color(106, 116, 145));
        buttons_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-Guardar Filled-50.png"))); // NOI18N
        jb_guardar.setText("Guardar");
        jb_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarMouseClicked(evt);
            }
        });
        jb_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_guardarActionPerformed(evt);
            }
        });
        buttons_2.add(jb_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jb_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel.png"))); // NOI18N
        jb_cancelar.setText("Cancelar");
        jb_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelarActionPerformed(evt);
            }
        });
        buttons_2.add(jb_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 47));

        jb_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ciclo.png"))); // NOI18N
        jb_actualizar.setText("Actualizar");
        jb_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_actualizarMouseClicked(evt);
            }
        });
        jb_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_actualizarActionPerformed(evt);
            }
        });
        buttons_2.add(jb_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 120, -1));

        jb_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trash.png"))); // NOI18N
        jb_borrar.setText("Borrar");
        jb_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_borrarMouseClicked(evt);
            }
        });
        buttons_2.add(jb_borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jb_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit.png"))); // NOI18N
        jb_editar.setText("Editar");
        jb_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_editarMouseClicked(evt);
            }
        });
        buttons_2.add(jb_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jb_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/new.png"))); // NOI18N
        jb_nuevo.setText("Nuevo");
        jb_nuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_nuevoMouseClicked(evt);
            }
        });
        buttons_2.add(jb_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jb_asignar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/edit.png"))); // NOI18N
        jb_asignar.setText("Editar/Asignar Alumnos");
        jb_asignar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_asignarMouseClicked(evt);
            }
        });
        buttons_2.add(jb_asignar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        panel_tabla.add(buttons_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 130, 220, 330));

        jb_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/home.png"))); // NOI18N
        jb_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_regresarActionPerformed(evt);
            }
        });
        panel_tabla.add(jb_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 16, 50, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jb_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        jb_buscar.setText("Buscar Registro");
        jb_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_buscarMouseClicked(evt);
            }
        });
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed(evt);
            }
        });

        jtf_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_buscarKeyTyped(evt);
            }
        });

        jp_hijos.setBackground(new java.awt.Color(255, 255, 255));

        jb_agregar.setText("Agregar");
        jb_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarMouseClicked(evt);
            }
        });

        jcb_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_alumnoActionPerformed(evt);
            }
        });

        jb_quitar.setText("Quitar asignación");
        jb_quitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_quitarMouseClicked(evt);
            }
        });
        jb_quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_quitarActionPerformed(evt);
            }
        });

        jl_alumno.setText("Alumno:");

        jl_alumnos.setText("Seleccione el(los) alumnos a cargo del tutor:");

        javax.swing.GroupLayout jp_hijosLayout = new javax.swing.GroupLayout(jp_hijos);
        jp_hijos.setLayout(jp_hijosLayout);
        jp_hijosLayout.setHorizontalGroup(
            jp_hijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_hijosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_hijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_hijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jtf_id_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jp_hijosLayout.createSequentialGroup()
                            .addComponent(jl_alumno)
                            .addGap(26, 26, 26)
                            .addComponent(jcb_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jcb_id_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jl_alumnos))
                .addGap(44, 44, 44)
                .addGroup(jp_hijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_agregar)
                    .addComponent(jb_quitar))
                .addContainerGap())
        );
        jp_hijosLayout.setVerticalGroup(
            jp_hijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_hijosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_hijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_alumnos)
                    .addComponent(jb_agregar))
                .addGap(18, 18, 18)
                .addGroup(jp_hijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_alumno)
                    .addComponent(jcb_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_id_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_quitar))
                .addGap(15, 15, 15)
                .addComponent(jtf_id_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jt_tutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt_tutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_tutorMouseClicked(evt);
            }
        });
        jt_tutores.setViewportView(jt_tutor);

        jt_relacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jt_relacion);

        jl_hijos.setForeground(new java.awt.Color(0, 0, 204));
        jl_hijos.setText("Nombre y apellidos del alumno");

        jl_tutores.setForeground(new java.awt.Color(0, 0, 204));
        jl_tutores.setText("Nombre y apellidos del Tutor");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jp_hijos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jt_tutores, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 32, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jb_buscar)
                                .addGap(18, 18, 18)
                                .addComponent(jtf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jl_hijos)
                .addGap(187, 187, 187)
                .addComponent(jl_tutores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_buscar)
                    .addComponent(jtf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jp_hijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jt_tutores, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_hijos)
                    .addComponent(jl_tutores))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jScrollPane6.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_tabla, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_buscarMouseClicked
        if (this.jb_buscar.isEnabled()) {
            buscar();
        } else {
        }
    }//GEN-LAST:event_jb_buscarMouseClicked

    private void jb_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_buscarActionPerformed

    private void jtf_buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_buscarKeyTyped
        char cadena = evt.getKeyChar();
        if (Character.isLowerCase(cadena)) {
            String cad = ("" + cadena).toUpperCase();
            cadena = cad.charAt(0);
            evt.setKeyChar(cadena);
        }
    }//GEN-LAST:event_jtf_buscarKeyTyped

    private void jb_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarMouseClicked
        if (this.jb_agregar.isEnabled()) {
            asignar();
        } else {
        }
    }//GEN-LAST:event_jb_agregarMouseClicked

    private void jcb_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_alumnoActionPerformed
        try {
            int index = this.jcb_alumno.getSelectedIndex();
            this.jtf_id_alumno.setText("" + index);
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/sistema_gmg", "root", "1405");
            st = conexion.createStatement();
            this.jcb_id_alumno.setSelectedIndex(index);

        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jcb_alumnoActionPerformed

    private void jb_quitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_quitarMouseClicked
        if (this.jb_quitar.isEnabled()) {
            quitar();
        } else {
        }
    }//GEN-LAST:event_jb_quitarMouseClicked

    private void jb_quitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_quitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_quitarActionPerformed

    private void jt_tutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_tutorMouseClicked
        tabla();
    }//GEN-LAST:event_jt_tutorMouseClicked

    private void jb_siguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_siguienteMouseClicked
        if (this.jb_siguiente.isEnabled()) {
            siguiente_registro();
        } else {
        }
    }//GEN-LAST:event_jb_siguienteMouseClicked

    private void jb_ultimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_ultimoMouseClicked
        if (this.jb_ultimo.isEnabled()) {
            ultimo_registro();
        } else {
        }
    }//GEN-LAST:event_jb_ultimoMouseClicked

    private void jb_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ultimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_ultimoActionPerformed

    private void jb_primeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_primeroMouseClicked
        if (this.jb_primero.isEnabled()) {
            primer_registro();
        } else {
        }
    }//GEN-LAST:event_jb_primeroMouseClicked

    private void jb_anteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_anteriorMouseClicked
        //se tiene que poner a todos los eventos mouse clicked condicion if
        if (this.jb_anterior.isEnabled()) {
            anterior_registro();
        } else {
        }
    }//GEN-LAST:event_jb_anteriorMouseClicked

    private void jb_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarMouseClicked
        if (this.jb_guardar.isEnabled()) {
            guardar_registro();
        } else {
        }
    }//GEN-LAST:event_jb_guardarMouseClicked

    private void jb_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_guardarActionPerformed

    private void jb_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelarActionPerformed
        if (this.jb_cancelar.isEnabled()) {
            Conectar();
        } else {
        }
    }//GEN-LAST:event_jb_cancelarActionPerformed

    private void jb_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_actualizarMouseClicked
       if (this.jb_actualizar.isEnabled()) {
            /*no agregar esta parte*/ String registro = this.jtf_nombre_tutor.getText();
            int alerta = JOptionPane.showConfirmDialog(null, "¿Quiere actualizar el registro del tutor " + registro + "?", "Actualizar", JOptionPane.WARNING_MESSAGE, JOptionPane.INFORMATION_MESSAGE);
            if (JOptionPane.OK_OPTION == alerta) {                
                actualizar_registro();

            } else {

            }
        } else {
        }
    }//GEN-LAST:event_jb_actualizarMouseClicked

    private void jb_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_actualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_actualizarActionPerformed

    private void jb_borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_borrarMouseClicked
       if (this.jb_borrar.isEnabled()) {
        String registro = this.jtf_nombre_tutor.getText();

            int alerta = JOptionPane.showConfirmDialog(null, "¿Quiere eliminar el registro del tutor: " + registro + "?", "Se borrarrá el registro", JOptionPane.WARNING_MESSAGE, JOptionPane.ERROR_MESSAGE);

            if (JOptionPane.OK_OPTION == alerta) {                
                borrar_registro();
            } else {

            }
        } else {
        }
    }//GEN-LAST:event_jb_borrarMouseClicked

    private void jb_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_editarMouseClicked
        if (this.jb_editar.isEnabled()) {

            
            jtf_nombre_tutor.setEditable(true);
            jtf_apellido_paterno_tut.setEditable(true);
            jtf_apellido_materno_tut.setEditable(true);
            jtf_calle.setEditable(true);
            jtf_colonia.setEditable(true);
            jtf_codigo_postal.setEditable(true);
            jtf_tel_casa.setEditable(true);
            jtf_tel_celular.setEditable(true);
            jtf_tel_emergencia.setEditable(true);
            jtf_no_casa.setEditable(true);

            jb_editar.setEnabled(false);
            jb_primero.setEnabled(false);
            jb_ultimo.setEnabled(false);
            jb_siguiente.setEnabled(false);
            jb_anterior.setEnabled(false);
            jb_buscar.setEnabled(false);
            jb_borrar.setEnabled(false);
            jb_actualizar.setEnabled(true);
            jb_cancelar.setEnabled(true);
            jb_guardar.setEnabled(false);
            jb_nuevo.setEnabled(false);
        } else {
        }
    }//GEN-LAST:event_jb_editarMouseClicked

    private void jb_nuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_nuevoMouseClicked
        if (this.jb_nuevo.isEnabled()) {
            nuevo_registro();
        } else {
        }
    }//GEN-LAST:event_jb_nuevoMouseClicked

    private void jb_asignarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_asignarMouseClicked
        if (this.jb_asignar.isEnabled()) {
            jp_hijos.setVisible(true);
        } else {
        }
    }//GEN-LAST:event_jb_asignarMouseClicked

    private void jb_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_regresarActionPerformed

        JF_Principal principal = new JF_Principal();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jb_regresarActionPerformed

    private void jtf_nombre_tutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nombre_tutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nombre_tutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Tutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Tutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Tutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Tutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Tutores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttons_2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jb_actualizar;
    private javax.swing.JButton jb_agregar;
    private javax.swing.JButton jb_anterior;
    private javax.swing.JButton jb_asignar;
    private javax.swing.JButton jb_borrar;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_editar;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_nuevo;
    private javax.swing.JButton jb_primero;
    private javax.swing.JButton jb_quitar;
    private javax.swing.JButton jb_regresar;
    private javax.swing.JButton jb_siguiente;
    private javax.swing.JButton jb_ultimo;
    private javax.swing.JComboBox<String> jcb_alumno;
    private javax.swing.JComboBox<String> jcb_id_alumno;
    private javax.swing.JLabel jl_alumno;
    private javax.swing.JLabel jl_alumnos;
    private javax.swing.JLabel jl_ap_materno_tut;
    private javax.swing.JLabel jl_ap_paterno_tut;
    private javax.swing.JLabel jl_calle;
    private javax.swing.JLabel jl_codigo_postal;
    private javax.swing.JLabel jl_colonia;
    private javax.swing.JLabel jl_hijos;
    private javax.swing.JLabel jl_menu;
    private javax.swing.JLabel jl_no_casa;
    private javax.swing.JLabel jl_nombre_tutor;
    private javax.swing.JLabel jl_tel_alternativo;
    private javax.swing.JLabel jl_tel_casa;
    private javax.swing.JLabel jl_tel_celular;
    private javax.swing.JLabel jl_tutores;
    private javax.swing.JPanel jp_hijos;
    private javax.swing.JTable jt_relacion;
    private javax.swing.JTable jt_tutor;
    private javax.swing.JScrollPane jt_tutores;
    private javax.swing.JTextField jtf_apellido_materno_tut;
    private javax.swing.JTextField jtf_apellido_paterno_tut;
    private javax.swing.JTextField jtf_buscar;
    private javax.swing.JTextField jtf_calle;
    private javax.swing.JTextField jtf_codigo_postal;
    private javax.swing.JTextField jtf_colonia;
    private javax.swing.JTextField jtf_id_alumno;
    private javax.swing.JTextField jtf_id_tutor;
    private javax.swing.JTextField jtf_no_casa;
    private javax.swing.JTextField jtf_nombre_tutor;
    private javax.swing.JTextField jtf_tel_casa;
    private javax.swing.JTextField jtf_tel_celular;
    private javax.swing.JTextField jtf_tel_emergencia;
    private javax.swing.JPanel panel_tabla;
    // End of variables declaration//GEN-END:variables

    private void nuevo_registro() {
        jtf_id_tutor.setText(null);
        jtf_nombre_tutor.setText(null);
        jtf_apellido_paterno_tut.setText(null);
        jtf_apellido_materno_tut.setText(null);
        jtf_calle.setText(null);
        jtf_colonia.setText(null);
        jtf_codigo_postal.setText(null);
        jtf_tel_casa.setText(null);
        jtf_tel_celular.setText(null);
        jtf_tel_emergencia.setText(null);
        jtf_no_casa.setText(null);
            
            jtf_nombre_tutor.setEditable(true);
            jtf_apellido_paterno_tut.setEditable(true);
            jtf_apellido_materno_tut.setEditable(true);
            jtf_calle.setEditable(true);
            jtf_colonia.setEditable(true);
            jtf_codigo_postal.setEditable(true);
            jtf_tel_casa.setEditable(true);
            jtf_tel_celular.setEditable(true);
            jtf_tel_emergencia.setEditable(true);
            jtf_no_casa.setEditable(true);
            
        jb_primero.setEnabled(false);
        jb_ultimo.setEnabled(false);
        jb_siguiente.setEnabled(false);
        jb_anterior.setEnabled(false);
        jb_buscar.setEnabled(false);
        jb_borrar.setEnabled(false);
        jb_actualizar.setEnabled(false);
        jb_cancelar.setEnabled(true);
        jb_guardar.setEnabled(true);
        jb_editar.setEnabled(false);
        jb_asignar.setEnabled(false);
        
    }

    private void actualizar_registro() {
        try {
            String registro = this.jtf_nombre_tutor.getText();
            jtf_nombre_tutor.getText();
            jtf_apellido_paterno_tut.getText();
            jtf_apellido_materno_tut.getText();
            jtf_calle.getText();
            jtf_colonia.getText();
            jtf_codigo_postal.getText();
            jtf_tel_casa.getText();
            jtf_tel_celular.getText();
            jtf_tel_emergencia.getText();

            st.executeUpdate("update tutor set nombre_tutor= '" + jtf_nombre_tutor.getText()
                    + "', apellido_paterno_tut = '" + jtf_apellido_paterno_tut.getText() + "', apellido_materno_tut = '" + jtf_apellido_materno_tut.getText()
                    + "', calle = '" + jtf_calle.getText() + "', colonia = '" + jtf_colonia.getText() + "', codigo_postal = '" + jtf_codigo_postal.getText()
                    + "', tel_casa = '" + jtf_tel_casa.getText()  + "', tel_celular = '" + jtf_tel_celular.getText() + "', tel_emergencia = '" + jtf_tel_emergencia.getText() 
                    + "' where id_tutor= "
                    + this.jtf_id_tutor.getText());
            JOptionPane.showMessageDialog(null, "Se actualizó el registro del tutor: " + registro + " exitosamente", "Actualizado", JOptionPane.INFORMATION_MESSAGE);
            Conectar();
            this.primer_registro();

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Rellene correctamente los campos", "Error al actualizar", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void guardar_registro() {
        try {
            String nombre_tutor = this.jtf_nombre_tutor.getText();
            String apellido_paterno_tut = this.jtf_apellido_paterno_tut.getText();
            String apellido_materno_tut = this.jtf_apellido_materno_tut.getText();
            String calle = this.jtf_calle.getText();
            String colonia = this.jtf_colonia.getText();
            String codigo_postal = this.jtf_codigo_postal.getText();
            String tel_casa = this.jtf_tel_casa.getText();
            String tel_celular = this.jtf_tel_celular.getText();
            String tel_emergencia = this.jtf_tel_emergencia.getText();
            String no_casa = this.jtf_no_casa.getText();            

            st.executeUpdate("Insert into tutor(nombre_tutor,apellido_paterno_tut,apellido_materno_tut,calle,colonia,no_casa,codigo_postal,tel_casa,tel_celular,tel_emergencia)" + "values "
                    + "('" + nombre_tutor + "','" + apellido_paterno_tut + "','" + apellido_materno_tut + "','" + calle + "','" + colonia + "','" + no_casa+"','" + codigo_postal + "','" + tel_casa + "','" + tel_celular + "','" + tel_emergencia + "');");
            
            JOptionPane.showMessageDialog(null, "Registro Guardado Exitosamente", "Guardado", JOptionPane.INFORMATION_MESSAGE);
            Conectar();
            this.primer_registro();

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }

    }

    private void siguiente_registro() {
        try {
            if (rs.isLast() == false) {
                rs.next();
                this.jtf_id_tutor.setText(rs.getString("id_tutor"));
                this.jtf_nombre_tutor.setText(rs.getString("nombre_tutor"));
                this.jtf_apellido_paterno_tut.setText(rs.getString("apellido_paterno_tut"));
                this.jtf_apellido_materno_tut.setText(rs.getString("apellido_materno_tut"));
                this.jtf_calle.setText(rs.getString("calle"));
                this.jtf_colonia.setText(rs.getString("colonia"));
                this.jtf_no_casa.setText(rs.getString("no_casa"));
                this.jtf_codigo_postal.setText(rs.getString("codigo_postal"));
                this.jtf_tel_casa.setText(rs.getString("tel_casa"));
                this.jtf_tel_celular.setText(rs.getString("tel_celular"));
                this.jtf_tel_emergencia.setText(rs.getString("tel_emergencia"));
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }

    private void anterior_registro() {
        try {
            if (rs.isFirst() == false) {
                rs.previous();
                this.jtf_id_tutor.setText(rs.getString("id_tutor"));
                this.jtf_nombre_tutor.setText(rs.getString("nombre_tutor"));
                this.jtf_apellido_paterno_tut.setText(rs.getString("apellido_paterno_tut"));
                this.jtf_apellido_materno_tut.setText(rs.getString("apellido_materno_tut"));
                this.jtf_calle.setText(rs.getString("calle"));
                this.jtf_colonia.setText(rs.getString("colonia"));
                this.jtf_no_casa.setText(rs.getString("no_casa"));
                this.jtf_codigo_postal.setText(rs.getString("codigo_postal"));
                this.jtf_tel_casa.setText(rs.getString("tel_casa"));
                this.jtf_tel_celular.setText(rs.getString("tel_celular"));
                this.jtf_tel_emergencia.setText(rs.getString("tel_emergencia"));
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }

    private void ultimo_registro() {
        try {
            if (rs.isLast() == false) {
                rs.last();

                this.jtf_id_tutor.setText(rs.getString("id_tutor"));
                this.jtf_nombre_tutor.setText(rs.getString("nombre_tutor"));
                this.jtf_apellido_paterno_tut.setText(rs.getString("apellido_paterno_tut"));
                this.jtf_apellido_materno_tut.setText(rs.getString("apellido_materno_tut"));
                this.jtf_calle.setText(rs.getString("calle"));
                this.jtf_colonia.setText(rs.getString("colonia"));
                this.jtf_no_casa.setText(rs.getString("no_casa"));
                this.jtf_codigo_postal.setText(rs.getString("codigo_postal"));
                this.jtf_tel_casa.setText(rs.getString("tel_casa"));
                this.jtf_tel_celular.setText(rs.getString("tel_celular"));
                this.jtf_tel_emergencia.setText(rs.getString("tel_emergencia"));

            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }

    private void primer_registro() {
        try {
            if (rs.isFirst() == false) {
                rs.first();
                this.jtf_id_tutor.setText(rs.getString("id_tutor"));
                this.jtf_nombre_tutor.setText(rs.getString("nombre_tutor"));
                this.jtf_apellido_paterno_tut.setText(rs.getString("apellido_paterno_tut"));
                this.jtf_apellido_materno_tut.setText(rs.getString("apellido_materno_tut"));
                this.jtf_calle.setText(rs.getString("calle"));
                this.jtf_colonia.setText(rs.getString("colonia"));
                this.jtf_no_casa.setText(rs.getString("no_casa"));
                this.jtf_codigo_postal.setText(rs.getString("codigo_postal"));
                this.jtf_tel_casa.setText(rs.getString("tel_casa"));
                this.jtf_tel_celular.setText(rs.getString("tel_celular"));
                this.jtf_tel_emergencia.setText(rs.getString("tel_emergencia"));

            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
        }
    }

    private void borrar_registro() {
        try {
            String registro = this.jtf_nombre_tutor.getText();
            st.executeUpdate("delete from tutor where id_tutor=" + this.jtf_id_tutor.getText());
            Conectar();
            JOptionPane.showMessageDialog(null, "Se borro el registro del tutor: " + registro + "", "Eliminado", JOptionPane.WARNING_MESSAGE);
            this.primer_registro();            
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "No se ha podido borrar el registro debido a que esta vinculado con un alumno (elimine primero la asignación)", "Error al borrar", JOptionPane.ERROR_MESSAGE);

        }
    }

    private void tabla() {        
        try {
            int seleccion = jt_tutor.getSelectedRow();

            jtf_id_tutor.setText(String.valueOf(jt_tutor.getValueAt(seleccion, 0)));
            jtf_nombre_tutor.setText(String.valueOf(jt_tutor.getValueAt(seleccion, 1)));
            jtf_apellido_paterno_tut.setText(String.valueOf(jt_tutor.getValueAt(seleccion, 2)));
            jtf_apellido_materno_tut.setText(String.valueOf(jt_tutor.getValueAt(seleccion, 3)));
            jtf_calle.setText(String.valueOf(jt_tutor.getValueAt(seleccion, 4)));
            jtf_colonia.setText(String.valueOf(jt_tutor.getValueAt(seleccion, 5)));
            jtf_no_casa.setText(String.valueOf(jt_tutor.getValueAt(seleccion,6)));
            jtf_codigo_postal.setText(String.valueOf(jt_tutor.getValueAt(seleccion, 7)));
            jtf_tel_casa.setText(String.valueOf(jt_tutor.getValueAt(seleccion, 8)));
            jtf_tel_celular.setText(String.valueOf(jt_tutor.getValueAt(seleccion, 9)));
            jtf_tel_emergencia.setText(String.valueOf(jt_tutor.getValueAt(seleccion,10)));

            rs = st.executeQuery("Select * from tutor");
            jt_tutor.setModel(DbUtils.resultSetToTableModel(rs));
            rs = st.executeQuery("Select * from tutor");
        } catch (SQLException ex) {
            Logger.getLogger(JF_Alumnos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }    

    private void asignar() {
        try {
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/sistema_gmg", "root", "1405");
            st = conexion.createStatement();

            st.executeUpdate("insert into relacion_tutor_alum (id_tutor,id_alumno) values('" + this.jtf_id_tutor.getText() + "', '" + this.jcb_id_alumno.getSelectedItem() + "');");
            JOptionPane.showMessageDialog(null, "Se asigno tutor al alumno '" +this.jcb_alumno.getSelectedItem()+ "' correctamente", "Asignado", JOptionPane.INFORMATION_MESSAGE);
            Conectar();
        } catch (SQLException err) {
        //JOptionPane.showMessageDialog(null, "Error " + err.getMessage());
JOptionPane.showMessageDialog(null, "La relación que intenta asignar ya ha sido asignado", "Error al asignar", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void quitar() {
        try {
            String registro = (String) this.jcb_alumno.getSelectedItem();
            st.executeUpdate("delete from relacion_tutor_alum  where id_tutor= '" + this.jtf_id_tutor.getText() +",'and id_alumno='" +this.jcb_id_alumno.getSelectedItem() + "'; ");
            JOptionPane.showMessageDialog(null, "Se borró la asignacion del alumno " + registro + " correctamente", "Eliminado", JOptionPane.WARNING_MESSAGE);
            Conectar();


        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, "El alumno no ha sido asignado a este tutor", "Error al borrar", JOptionPane.ERROR_MESSAGE);

        }
    }

    private void buscar() {
        try {
            rs = st.executeQuery("select * from tutores where nombre_tutor like '" + this.jtf_buscar.getText() + "%'");

            jtf_id_tutor.setText(null);
            jtf_nombre_tutor.setText(null);
            jtf_apellido_paterno_tut.setText(null);
            jtf_apellido_materno_tut.setText(null);
            jtf_calle.setText(null);
            jtf_colonia.setText(null);
            jtf_no_casa.setText(null);
            jtf_codigo_postal.setText(null);
            jtf_tel_emergencia.setText(null);
            jtf_tel_casa.setText(null);
            jtf_tel_celular.setText(null);
            jtf_codigo_postal.setText(null);
            
            jt_tutor.setModel(DbUtils.resultSetToTableModel(rs));

            jb_cancelar.setEnabled(true);
            rs = st.executeQuery("select *from alumnos");
        } catch (SQLException ex) {
            Logger.getLogger(JF_Alumnos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
