/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Mike
 */
public class View_Inicio extends javax.swing.JPanel {

    /**
     * Creates new form View_Inicio
     */
    public View_Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_salir = new javax.swing.JButton();
        jb_alumnos = new javax.swing.JButton();
        jb_ciclos = new javax.swing.JButton();
        jb_calificaciones = new javax.swing.JButton();
        jb_tutores = new javax.swing.JButton();
        jb_administrar = new javax.swing.JButton();
        jb_inscripciones = new javax.swing.JButton();
        jb_periodo = new javax.swing.JButton();
        jb_grupos = new javax.swing.JButton();
        jb_profesores = new javax.swing.JButton();

        jb_salir.setText("Salir");

        jb_alumnos.setText("Alumnos");

        jb_ciclos.setText("Ciclos");

        jb_calificaciones.setText("Calificaciones");

        jb_tutores.setText("Tutores");

        jb_administrar.setText("Administrar cuentas");

        jb_inscripciones.setText("Inscripciones");

        jb_periodo.setText("Periodo de Calificaciones");

        jb_grupos.setText("Grupos");

        jb_profesores.setText("Profesores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_alumnos)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jb_ciclos)
                                    .addComponent(jb_tutores))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 347, Short.MAX_VALUE)
                                .addComponent(jb_salir))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_inscripciones)
                            .addComponent(jb_calificaciones)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jb_administrar))
                    .addComponent(jb_periodo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jb_grupos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jb_profesores)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jb_ciclos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jb_salir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_tutores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_alumnos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_calificaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_inscripciones)
                .addGap(7, 7, 7)
                .addComponent(jb_administrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_periodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_grupos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_profesores)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jb_administrar;
    public javax.swing.JButton jb_alumnos;
    public javax.swing.JButton jb_calificaciones;
    public javax.swing.JButton jb_ciclos;
    public javax.swing.JButton jb_grupos;
    public javax.swing.JButton jb_inscripciones;
    public javax.swing.JButton jb_periodo;
    public javax.swing.JButton jb_profesores;
    public javax.swing.JButton jb_salir;
    public javax.swing.JButton jb_tutores;
    // End of variables declaration//GEN-END:variables
}
