/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Mike
 */
public class View_Ciclos extends javax.swing.JPanel {

    /**
     * Creates new form View_Ciclos
     */
    public View_Ciclos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_titulo = new javax.swing.JLabel();
        jb_regresar = new javax.swing.JButton();
        jb_salir = new javax.swing.JButton();
        jl_ciclo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jl_fecha_termino = new javax.swing.JLabel();
        jtf_ciclo = new javax.swing.JTextField();
        jtf_fecha_inicio = new javax.swing.JTextField();
        jtf_fecha_termino = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_ciclos = new javax.swing.JTable();
        jdc_fecha_inicio = new com.toedter.calendar.JDateChooser();
        jdc_fecha_termino = new com.toedter.calendar.JDateChooser();
        jtf_id_ciclo = new javax.swing.JTextField();
        jb_ultimo = new javax.swing.JButton();
        jb_siguiente = new javax.swing.JButton();
        jb_anterior = new javax.swing.JButton();
        jb_primero = new javax.swing.JButton();
        jb_nuevo = new javax.swing.JButton();
        jb_actualizar = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();
        jb_eliminar = new javax.swing.JButton();
        jb_guardar = new javax.swing.JButton();
        jb_editar = new javax.swing.JButton();
        jb_buscar = new javax.swing.JButton();
        jtf_buscar = new javax.swing.JTextField();

        jl_titulo.setFont(new java.awt.Font("Comfortaa Light", 0, 24)); // NOI18N
        jl_titulo.setText("Ciclos");

        jb_regresar.setText("Regresar");

        jb_salir.setText("Salir");

        jl_ciclo.setFont(new java.awt.Font("Comfortaa Light", 0, 18)); // NOI18N
        jl_ciclo.setText("Ciclo");

        jLabel3.setFont(new java.awt.Font("Comfortaa Light", 0, 18)); // NOI18N
        jLabel3.setText("Fecha de Inicio");

        jl_fecha_termino.setFont(new java.awt.Font("Comfortaa Light", 0, 18)); // NOI18N
        jl_fecha_termino.setText("Fecha de termino");

        jtf_ciclo.setFont(new java.awt.Font("Comfortaa Light", 0, 15)); // NOI18N

        jtf_fecha_inicio.setFont(new java.awt.Font("Comfortaa Light", 0, 15)); // NOI18N

        jtf_fecha_termino.setFont(new java.awt.Font("Comfortaa Light", 0, 15)); // NOI18N

        jt_ciclos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jt_ciclos);

        jb_ultimo.setText(">|");

        jb_siguiente.setText(">>");

        jb_anterior.setText("<<");

        jb_primero.setText("|<");

        jb_nuevo.setText("Nuevo");

        jb_actualizar.setText("Actualizar");

        jb_cancelar.setText("Cancelar");

        jb_eliminar.setText("Eliminar");

        jb_guardar.setText("Guardar");

        jb_editar.setText("Editar");

        jb_buscar.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jb_regresar)
                .addGap(150, 150, 150)
                .addComponent(jl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_salir)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_ciclo)
                                    .addComponent(jl_fecha_termino)
                                    .addComponent(jLabel3))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtf_fecha_inicio)
                                    .addComponent(jtf_ciclo, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(jtf_fecha_termino))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jdc_fecha_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(jdc_fecha_termino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 95, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtf_id_ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_primero)
                        .addGap(4, 4, 4)
                        .addComponent(jb_anterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_siguiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jb_eliminar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_nuevo)
                        .addGap(18, 18, 18)
                        .addComponent(jb_actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_guardar)
                        .addGap(18, 18, 18)
                        .addComponent(jb_editar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_regresar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtf_id_ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jb_salir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_ultimo)
                            .addComponent(jb_siguiente)
                            .addComponent(jb_anterior)
                            .addComponent(jb_primero))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jb_guardar)
                        .addComponent(jb_editar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jb_nuevo)
                        .addComponent(jb_actualizar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_cancelar)
                    .addComponent(jb_eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl_ciclo)
                    .addComponent(jtf_ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtf_fecha_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jl_fecha_termino)
                                .addComponent(jtf_fecha_termino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jdc_fecha_termino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jdc_fecha_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_buscar)
                    .addComponent(jtf_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel3;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jb_actualizar;
    public javax.swing.JButton jb_anterior;
    public javax.swing.JButton jb_buscar;
    public javax.swing.JButton jb_cancelar;
    public javax.swing.JButton jb_editar;
    public javax.swing.JButton jb_eliminar;
    public javax.swing.JButton jb_guardar;
    public javax.swing.JButton jb_nuevo;
    public javax.swing.JButton jb_primero;
    public javax.swing.JButton jb_regresar;
    public javax.swing.JButton jb_salir;
    public javax.swing.JButton jb_siguiente;
    public javax.swing.JButton jb_ultimo;
    public com.toedter.calendar.JDateChooser jdc_fecha_inicio;
    public com.toedter.calendar.JDateChooser jdc_fecha_termino;
    public javax.swing.JLabel jl_ciclo;
    public javax.swing.JLabel jl_fecha_termino;
    public javax.swing.JLabel jl_titulo;
    public javax.swing.JTable jt_ciclos;
    public javax.swing.JTextField jtf_buscar;
    public javax.swing.JTextField jtf_ciclo;
    public javax.swing.JTextField jtf_fecha_inicio;
    public javax.swing.JTextField jtf_fecha_termino;
    public javax.swing.JTextField jtf_id_ciclo;
    // End of variables declaration//GEN-END:variables
}
